// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.2
// source: parser_service.proto

package parserservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ParserService_ParseDocument_FullMethodName = "/ai_platform.parser_service.ParserService/ParseDocument"
	ParserService_ParseText_FullMethodName     = "/ai_platform.parser_service.ParserService/ParseText"
	ParserService_ExtractTables_FullMethodName = "/ai_platform.parser_service.ParserService/ExtractTables"
	ParserService_ExtractImages_FullMethodName = "/ai_platform.parser_service.ParserService/ExtractImages"
	ParserService_ExtractOCR_FullMethodName    = "/ai_platform.parser_service.ParserService/ExtractOCR"
	ParserService_DetectLayout_FullMethodName  = "/ai_platform.parser_service.ParserService/DetectLayout"
)

// ParserServiceClient is the client API for ParserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Parser Service - Fase 2.1
type ParserServiceClient interface {
	ParseDocument(ctx context.Context, in *ParseDocumentRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error)
	ParseText(ctx context.Context, in *ParseTextRequest, opts ...grpc.CallOption) (*ParseTextResponse, error)
	ExtractTables(ctx context.Context, in *ExtractTablesRequest, opts ...grpc.CallOption) (*ExtractTablesResponse, error)
	ExtractImages(ctx context.Context, in *ExtractImagesRequest, opts ...grpc.CallOption) (*ExtractImagesResponse, error)
	ExtractOCR(ctx context.Context, in *ExtractOCRRequest, opts ...grpc.CallOption) (*ExtractOCRResponse, error)
	DetectLayout(ctx context.Context, in *DetectLayoutRequest, opts ...grpc.CallOption) (*DetectLayoutResponse, error)
}

type parserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewParserServiceClient(cc grpc.ClientConnInterface) ParserServiceClient {
	return &parserServiceClient{cc}
}

func (c *parserServiceClient) ParseDocument(ctx context.Context, in *ParseDocumentRequest, opts ...grpc.CallOption) (*ParseDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseDocumentResponse)
	err := c.cc.Invoke(ctx, ParserService_ParseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parserServiceClient) ParseText(ctx context.Context, in *ParseTextRequest, opts ...grpc.CallOption) (*ParseTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseTextResponse)
	err := c.cc.Invoke(ctx, ParserService_ParseText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parserServiceClient) ExtractTables(ctx context.Context, in *ExtractTablesRequest, opts ...grpc.CallOption) (*ExtractTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractTablesResponse)
	err := c.cc.Invoke(ctx, ParserService_ExtractTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parserServiceClient) ExtractImages(ctx context.Context, in *ExtractImagesRequest, opts ...grpc.CallOption) (*ExtractImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractImagesResponse)
	err := c.cc.Invoke(ctx, ParserService_ExtractImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parserServiceClient) ExtractOCR(ctx context.Context, in *ExtractOCRRequest, opts ...grpc.CallOption) (*ExtractOCRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtractOCRResponse)
	err := c.cc.Invoke(ctx, ParserService_ExtractOCR_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parserServiceClient) DetectLayout(ctx context.Context, in *DetectLayoutRequest, opts ...grpc.CallOption) (*DetectLayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectLayoutResponse)
	err := c.cc.Invoke(ctx, ParserService_DetectLayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ParserServiceServer is the server API for ParserService service.
// All implementations must embed UnimplementedParserServiceServer
// for forward compatibility.
//
// Parser Service - Fase 2.1
type ParserServiceServer interface {
	ParseDocument(context.Context, *ParseDocumentRequest) (*ParseDocumentResponse, error)
	ParseText(context.Context, *ParseTextRequest) (*ParseTextResponse, error)
	ExtractTables(context.Context, *ExtractTablesRequest) (*ExtractTablesResponse, error)
	ExtractImages(context.Context, *ExtractImagesRequest) (*ExtractImagesResponse, error)
	ExtractOCR(context.Context, *ExtractOCRRequest) (*ExtractOCRResponse, error)
	DetectLayout(context.Context, *DetectLayoutRequest) (*DetectLayoutResponse, error)
	mustEmbedUnimplementedParserServiceServer()
}

// UnimplementedParserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedParserServiceServer struct{}

func (UnimplementedParserServiceServer) ParseDocument(context.Context, *ParseDocumentRequest) (*ParseDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseDocument not implemented")
}
func (UnimplementedParserServiceServer) ParseText(context.Context, *ParseTextRequest) (*ParseTextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ParseText not implemented")
}
func (UnimplementedParserServiceServer) ExtractTables(context.Context, *ExtractTablesRequest) (*ExtractTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractTables not implemented")
}
func (UnimplementedParserServiceServer) ExtractImages(context.Context, *ExtractImagesRequest) (*ExtractImagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractImages not implemented")
}
func (UnimplementedParserServiceServer) ExtractOCR(context.Context, *ExtractOCRRequest) (*ExtractOCRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtractOCR not implemented")
}
func (UnimplementedParserServiceServer) DetectLayout(context.Context, *DetectLayoutRequest) (*DetectLayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectLayout not implemented")
}
func (UnimplementedParserServiceServer) mustEmbedUnimplementedParserServiceServer() {}
func (UnimplementedParserServiceServer) testEmbeddedByValue()                       {}

// UnsafeParserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ParserServiceServer will
// result in compilation errors.
type UnsafeParserServiceServer interface {
	mustEmbedUnimplementedParserServiceServer()
}

func RegisterParserServiceServer(s grpc.ServiceRegistrar, srv ParserServiceServer) {
	// If the following call panics, it indicates UnimplementedParserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ParserService_ServiceDesc, srv)
}

func _ParserService_ParseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ParseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ParseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ParseDocument(ctx, req.(*ParseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParserService_ParseText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ParseText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ParseText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ParseText(ctx, req.(*ParseTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParserService_ExtractTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ExtractTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ExtractTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ExtractTables(ctx, req.(*ExtractTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParserService_ExtractImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ExtractImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ExtractImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ExtractImages(ctx, req.(*ExtractImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParserService_ExtractOCR_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtractOCRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).ExtractOCR(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_ExtractOCR_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).ExtractOCR(ctx, req.(*ExtractOCRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParserService_DetectLayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectLayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParserServiceServer).DetectLayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ParserService_DetectLayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParserServiceServer).DetectLayout(ctx, req.(*DetectLayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ParserService_ServiceDesc is the grpc.ServiceDesc for ParserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ParserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_platform.parser_service.ParserService",
	HandlerType: (*ParserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseDocument",
			Handler:    _ParserService_ParseDocument_Handler,
		},
		{
			MethodName: "ParseText",
			Handler:    _ParserService_ParseText_Handler,
		},
		{
			MethodName: "ExtractTables",
			Handler:    _ParserService_ExtractTables_Handler,
		},
		{
			MethodName: "ExtractImages",
			Handler:    _ParserService_ExtractImages_Handler,
		},
		{
			MethodName: "ExtractOCR",
			Handler:    _ParserService_ExtractOCR_Handler,
		},
		{
			MethodName: "DetectLayout",
			Handler:    _ParserService_DetectLayout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parser_service.proto",
}
