# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vision_service_pb2 as vision__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub(object):
    """Vision Service - Fase 2.2
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessOCR = channel.unary_unary(
                '/ai_platform.vision_service.VisionService/ProcessOCR',
                request_serializer=vision__service__pb2.ProcessOCRRequest.SerializeToString,
                response_deserializer=vision__service__pb2.ProcessOCRResponse.FromString,
                _registered_method=True)
        self.AnalyzeDiagram = channel.unary_unary(
                '/ai_platform.vision_service.VisionService/AnalyzeDiagram',
                request_serializer=vision__service__pb2.AnalyzeDiagramRequest.SerializeToString,
                response_deserializer=vision__service__pb2.AnalyzeDiagramResponse.FromString,
                _registered_method=True)
        self.ExtractFormula = channel.unary_unary(
                '/ai_platform.vision_service.VisionService/ExtractFormula',
                request_serializer=vision__service__pb2.ExtractFormulaRequest.SerializeToString,
                response_deserializer=vision__service__pb2.ExtractFormulaResponse.FromString,
                _registered_method=True)
        self.ClassifyImage = channel.unary_unary(
                '/ai_platform.vision_service.VisionService/ClassifyImage',
                request_serializer=vision__service__pb2.ClassifyImageRequest.SerializeToString,
                response_deserializer=vision__service__pb2.ClassifyImageResponse.FromString,
                _registered_method=True)
        self.PreprocessImage = channel.unary_unary(
                '/ai_platform.vision_service.VisionService/PreprocessImage',
                request_serializer=vision__service__pb2.PreprocessImageRequest.SerializeToString,
                response_deserializer=vision__service__pb2.PreprocessImageResponse.FromString,
                _registered_method=True)


class VisionServiceServicer(object):
    """Vision Service - Fase 2.2
    """

    def ProcessOCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeDiagram(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractFormula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreprocessImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessOCR': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessOCR,
                    request_deserializer=vision__service__pb2.ProcessOCRRequest.FromString,
                    response_serializer=vision__service__pb2.ProcessOCRResponse.SerializeToString,
            ),
            'AnalyzeDiagram': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDiagram,
                    request_deserializer=vision__service__pb2.AnalyzeDiagramRequest.FromString,
                    response_serializer=vision__service__pb2.AnalyzeDiagramResponse.SerializeToString,
            ),
            'ExtractFormula': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractFormula,
                    request_deserializer=vision__service__pb2.ExtractFormulaRequest.FromString,
                    response_serializer=vision__service__pb2.ExtractFormulaResponse.SerializeToString,
            ),
            'ClassifyImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyImage,
                    request_deserializer=vision__service__pb2.ClassifyImageRequest.FromString,
                    response_serializer=vision__service__pb2.ClassifyImageResponse.SerializeToString,
            ),
            'PreprocessImage': grpc.unary_unary_rpc_method_handler(
                    servicer.PreprocessImage,
                    request_deserializer=vision__service__pb2.PreprocessImageRequest.FromString,
                    response_serializer=vision__service__pb2.PreprocessImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.vision_service.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.vision_service.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService(object):
    """Vision Service - Fase 2.2
    """

    @staticmethod
    def ProcessOCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.vision_service.VisionService/ProcessOCR',
            vision__service__pb2.ProcessOCRRequest.SerializeToString,
            vision__service__pb2.ProcessOCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeDiagram(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.vision_service.VisionService/AnalyzeDiagram',
            vision__service__pb2.AnalyzeDiagramRequest.SerializeToString,
            vision__service__pb2.AnalyzeDiagramResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractFormula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.vision_service.VisionService/ExtractFormula',
            vision__service__pb2.ExtractFormulaRequest.SerializeToString,
            vision__service__pb2.ExtractFormulaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.vision_service.VisionService/ClassifyImage',
            vision__service__pb2.ClassifyImageRequest.SerializeToString,
            vision__service__pb2.ClassifyImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreprocessImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.vision_service.VisionService/PreprocessImage',
            vision__service__pb2.PreprocessImageRequest.SerializeToString,
            vision__service__pb2.PreprocessImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
