receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp_http/grafana_cloud:
    endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}"
    headers:
      authorization: "${env:GRAFANA_CLOUD_BASIC_AUTH_HEADER}"

service:
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}/v1/metrics"
                headers:
                  - name: "authorization"
                    value: "${env:GRAFANA_CLOUD_BASIC_AUTH_HEADER}"
    logs:
      processors:
        - batch:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: "${env:GRAFANA_CLOUD_OTLP_ENDPOINT}/v1/logs"
                headers:
                  - name: "authorization"
                    value: "${env:GRAFANA_CLOUD_BASIC_AUTH_HEADER}"
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/grafana_cloud, debug]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/grafana_cloud, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp_http/grafana_cloud, debug]
