// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.2
// source: semantic_chunk_service.proto

package semanticchunkservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SemanticChunkService_ChunkCompetency_FullMethodName  = "/ai_platform.semantic_chunk_service.SemanticChunkService/ChunkCompetency"
	SemanticChunkService_ChunkActivity_FullMethodName    = "/ai_platform.semantic_chunk_service.SemanticChunkService/ChunkActivity"
	SemanticChunkService_ChunkAssessment_FullMethodName  = "/ai_platform.semantic_chunk_service.SemanticChunkService/ChunkAssessment"
	SemanticChunkService_ChunkInquiry_FullMethodName     = "/ai_platform.semantic_chunk_service.SemanticChunkService/ChunkInquiry"
	SemanticChunkService_ChunkLessonPlan_FullMethodName  = "/ai_platform.semantic_chunk_service.SemanticChunkService/ChunkLessonPlan"
	SemanticChunkService_DetectHierarchy_FullMethodName  = "/ai_platform.semantic_chunk_service.SemanticChunkService/DetectHierarchy"
	SemanticChunkService_ClassifyPedagogy_FullMethodName = "/ai_platform.semantic_chunk_service.SemanticChunkService/ClassifyPedagogy"
	SemanticChunkService_ValidateQuality_FullMethodName  = "/ai_platform.semantic_chunk_service.SemanticChunkService/ValidateQuality"
	SemanticChunkService_EnrichMetadata_FullMethodName   = "/ai_platform.semantic_chunk_service.SemanticChunkService/EnrichMetadata"
	SemanticChunkService_BuildChunks_FullMethodName      = "/ai_platform.semantic_chunk_service.SemanticChunkService/BuildChunks"
)

// SemanticChunkServiceClient is the client API for SemanticChunkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Semantic Chunk Service - Fase 2.3
type SemanticChunkServiceClient interface {
	ChunkCompetency(ctx context.Context, in *ChunkCompetencyRequest, opts ...grpc.CallOption) (*ChunkCompetencyResponse, error)
	ChunkActivity(ctx context.Context, in *ChunkActivityRequest, opts ...grpc.CallOption) (*ChunkActivityResponse, error)
	ChunkAssessment(ctx context.Context, in *ChunkAssessmentRequest, opts ...grpc.CallOption) (*ChunkAssessmentResponse, error)
	ChunkInquiry(ctx context.Context, in *ChunkInquiryRequest, opts ...grpc.CallOption) (*ChunkInquiryResponse, error)
	ChunkLessonPlan(ctx context.Context, in *ChunkLessonPlanRequest, opts ...grpc.CallOption) (*ChunkLessonPlanResponse, error)
	DetectHierarchy(ctx context.Context, in *DetectHierarchyRequest, opts ...grpc.CallOption) (*DetectHierarchyResponse, error)
	ClassifyPedagogy(ctx context.Context, in *ClassifyPedagogyRequest, opts ...grpc.CallOption) (*ClassifyPedagogyResponse, error)
	ValidateQuality(ctx context.Context, in *ValidateQualityRequest, opts ...grpc.CallOption) (*ValidateQualityResponse, error)
	EnrichMetadata(ctx context.Context, in *EnrichMetadataRequest, opts ...grpc.CallOption) (*EnrichMetadataResponse, error)
	BuildChunks(ctx context.Context, in *BuildChunksRequest, opts ...grpc.CallOption) (*BuildChunksResponse, error)
}

type semanticChunkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSemanticChunkServiceClient(cc grpc.ClientConnInterface) SemanticChunkServiceClient {
	return &semanticChunkServiceClient{cc}
}

func (c *semanticChunkServiceClient) ChunkCompetency(ctx context.Context, in *ChunkCompetencyRequest, opts ...grpc.CallOption) (*ChunkCompetencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkCompetencyResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ChunkCompetency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) ChunkActivity(ctx context.Context, in *ChunkActivityRequest, opts ...grpc.CallOption) (*ChunkActivityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkActivityResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ChunkActivity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) ChunkAssessment(ctx context.Context, in *ChunkAssessmentRequest, opts ...grpc.CallOption) (*ChunkAssessmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkAssessmentResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ChunkAssessment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) ChunkInquiry(ctx context.Context, in *ChunkInquiryRequest, opts ...grpc.CallOption) (*ChunkInquiryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkInquiryResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ChunkInquiry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) ChunkLessonPlan(ctx context.Context, in *ChunkLessonPlanRequest, opts ...grpc.CallOption) (*ChunkLessonPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChunkLessonPlanResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ChunkLessonPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) DetectHierarchy(ctx context.Context, in *DetectHierarchyRequest, opts ...grpc.CallOption) (*DetectHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectHierarchyResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_DetectHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) ClassifyPedagogy(ctx context.Context, in *ClassifyPedagogyRequest, opts ...grpc.CallOption) (*ClassifyPedagogyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassifyPedagogyResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ClassifyPedagogy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) ValidateQuality(ctx context.Context, in *ValidateQualityRequest, opts ...grpc.CallOption) (*ValidateQualityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateQualityResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_ValidateQuality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) EnrichMetadata(ctx context.Context, in *EnrichMetadataRequest, opts ...grpc.CallOption) (*EnrichMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrichMetadataResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_EnrichMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *semanticChunkServiceClient) BuildChunks(ctx context.Context, in *BuildChunksRequest, opts ...grpc.CallOption) (*BuildChunksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildChunksResponse)
	err := c.cc.Invoke(ctx, SemanticChunkService_BuildChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SemanticChunkServiceServer is the server API for SemanticChunkService service.
// All implementations must embed UnimplementedSemanticChunkServiceServer
// for forward compatibility.
//
// Semantic Chunk Service - Fase 2.3
type SemanticChunkServiceServer interface {
	ChunkCompetency(context.Context, *ChunkCompetencyRequest) (*ChunkCompetencyResponse, error)
	ChunkActivity(context.Context, *ChunkActivityRequest) (*ChunkActivityResponse, error)
	ChunkAssessment(context.Context, *ChunkAssessmentRequest) (*ChunkAssessmentResponse, error)
	ChunkInquiry(context.Context, *ChunkInquiryRequest) (*ChunkInquiryResponse, error)
	ChunkLessonPlan(context.Context, *ChunkLessonPlanRequest) (*ChunkLessonPlanResponse, error)
	DetectHierarchy(context.Context, *DetectHierarchyRequest) (*DetectHierarchyResponse, error)
	ClassifyPedagogy(context.Context, *ClassifyPedagogyRequest) (*ClassifyPedagogyResponse, error)
	ValidateQuality(context.Context, *ValidateQualityRequest) (*ValidateQualityResponse, error)
	EnrichMetadata(context.Context, *EnrichMetadataRequest) (*EnrichMetadataResponse, error)
	BuildChunks(context.Context, *BuildChunksRequest) (*BuildChunksResponse, error)
	mustEmbedUnimplementedSemanticChunkServiceServer()
}

// UnimplementedSemanticChunkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSemanticChunkServiceServer struct{}

func (UnimplementedSemanticChunkServiceServer) ChunkCompetency(context.Context, *ChunkCompetencyRequest) (*ChunkCompetencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkCompetency not implemented")
}
func (UnimplementedSemanticChunkServiceServer) ChunkActivity(context.Context, *ChunkActivityRequest) (*ChunkActivityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkActivity not implemented")
}
func (UnimplementedSemanticChunkServiceServer) ChunkAssessment(context.Context, *ChunkAssessmentRequest) (*ChunkAssessmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkAssessment not implemented")
}
func (UnimplementedSemanticChunkServiceServer) ChunkInquiry(context.Context, *ChunkInquiryRequest) (*ChunkInquiryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkInquiry not implemented")
}
func (UnimplementedSemanticChunkServiceServer) ChunkLessonPlan(context.Context, *ChunkLessonPlanRequest) (*ChunkLessonPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChunkLessonPlan not implemented")
}
func (UnimplementedSemanticChunkServiceServer) DetectHierarchy(context.Context, *DetectHierarchyRequest) (*DetectHierarchyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetectHierarchy not implemented")
}
func (UnimplementedSemanticChunkServiceServer) ClassifyPedagogy(context.Context, *ClassifyPedagogyRequest) (*ClassifyPedagogyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClassifyPedagogy not implemented")
}
func (UnimplementedSemanticChunkServiceServer) ValidateQuality(context.Context, *ValidateQualityRequest) (*ValidateQualityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateQuality not implemented")
}
func (UnimplementedSemanticChunkServiceServer) EnrichMetadata(context.Context, *EnrichMetadataRequest) (*EnrichMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnrichMetadata not implemented")
}
func (UnimplementedSemanticChunkServiceServer) BuildChunks(context.Context, *BuildChunksRequest) (*BuildChunksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildChunks not implemented")
}
func (UnimplementedSemanticChunkServiceServer) mustEmbedUnimplementedSemanticChunkServiceServer() {}
func (UnimplementedSemanticChunkServiceServer) testEmbeddedByValue()                              {}

// UnsafeSemanticChunkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SemanticChunkServiceServer will
// result in compilation errors.
type UnsafeSemanticChunkServiceServer interface {
	mustEmbedUnimplementedSemanticChunkServiceServer()
}

func RegisterSemanticChunkServiceServer(s grpc.ServiceRegistrar, srv SemanticChunkServiceServer) {
	// If the following call panics, it indicates UnimplementedSemanticChunkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SemanticChunkService_ServiceDesc, srv)
}

func _SemanticChunkService_ChunkCompetency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkCompetencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ChunkCompetency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ChunkCompetency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ChunkCompetency(ctx, req.(*ChunkCompetencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_ChunkActivity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkActivityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ChunkActivity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ChunkActivity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ChunkActivity(ctx, req.(*ChunkActivityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_ChunkAssessment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkAssessmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ChunkAssessment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ChunkAssessment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ChunkAssessment(ctx, req.(*ChunkAssessmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_ChunkInquiry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkInquiryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ChunkInquiry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ChunkInquiry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ChunkInquiry(ctx, req.(*ChunkInquiryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_ChunkLessonPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChunkLessonPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ChunkLessonPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ChunkLessonPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ChunkLessonPlan(ctx, req.(*ChunkLessonPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_DetectHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).DetectHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_DetectHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).DetectHierarchy(ctx, req.(*DetectHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_ClassifyPedagogy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassifyPedagogyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ClassifyPedagogy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ClassifyPedagogy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ClassifyPedagogy(ctx, req.(*ClassifyPedagogyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_ValidateQuality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateQualityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).ValidateQuality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_ValidateQuality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).ValidateQuality(ctx, req.(*ValidateQualityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_EnrichMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrichMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).EnrichMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_EnrichMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).EnrichMetadata(ctx, req.(*EnrichMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SemanticChunkService_BuildChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildChunksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SemanticChunkServiceServer).BuildChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SemanticChunkService_BuildChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SemanticChunkServiceServer).BuildChunks(ctx, req.(*BuildChunksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SemanticChunkService_ServiceDesc is the grpc.ServiceDesc for SemanticChunkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SemanticChunkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_platform.semantic_chunk_service.SemanticChunkService",
	HandlerType: (*SemanticChunkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChunkCompetency",
			Handler:    _SemanticChunkService_ChunkCompetency_Handler,
		},
		{
			MethodName: "ChunkActivity",
			Handler:    _SemanticChunkService_ChunkActivity_Handler,
		},
		{
			MethodName: "ChunkAssessment",
			Handler:    _SemanticChunkService_ChunkAssessment_Handler,
		},
		{
			MethodName: "ChunkInquiry",
			Handler:    _SemanticChunkService_ChunkInquiry_Handler,
		},
		{
			MethodName: "ChunkLessonPlan",
			Handler:    _SemanticChunkService_ChunkLessonPlan_Handler,
		},
		{
			MethodName: "DetectHierarchy",
			Handler:    _SemanticChunkService_DetectHierarchy_Handler,
		},
		{
			MethodName: "ClassifyPedagogy",
			Handler:    _SemanticChunkService_ClassifyPedagogy_Handler,
		},
		{
			MethodName: "ValidateQuality",
			Handler:    _SemanticChunkService_ValidateQuality_Handler,
		},
		{
			MethodName: "EnrichMetadata",
			Handler:    _SemanticChunkService_EnrichMetadata_Handler,
		},
		{
			MethodName: "BuildChunks",
			Handler:    _SemanticChunkService_BuildChunks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "semantic_chunk_service.proto",
}
