// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: reranking_service.proto

package rerankingservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reranking Service Messages
type RerankCrossEncoderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents      []*RetrievalResult     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	RerankingModel string                 `protobuf:"bytes,4,opt,name=reranking_model,json=rerankingModel,proto3" json:"reranking_model,omitempty"`
	TopK           int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options        map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RerankCrossEncoderRequest) Reset() {
	*x = RerankCrossEncoderRequest{}
	mi := &file_reranking_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankCrossEncoderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankCrossEncoderRequest) ProtoMessage() {}

func (x *RerankCrossEncoderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankCrossEncoderRequest.ProtoReflect.Descriptor instead.
func (*RerankCrossEncoderRequest) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{0}
}

func (x *RerankCrossEncoderRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *RerankCrossEncoderRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankCrossEncoderRequest) GetDocuments() []*RetrievalResult {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RerankCrossEncoderRequest) GetRerankingModel() string {
	if x != nil {
		return x.RerankingModel
	}
	return ""
}

func (x *RerankCrossEncoderRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RerankCrossEncoderRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RetrievalResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalResult) Reset() {
	*x = RetrievalResult{}
	mi := &file_reranking_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalResult) ProtoMessage() {}

func (x *RetrievalResult) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalResult.ProtoReflect.Descriptor instead.
func (*RetrievalResult) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{1}
}

func (x *RetrievalResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetrievalResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrievalResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievalResult) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RerankCrossEncoderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RerankingResult       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankCrossEncoderResponse) Reset() {
	*x = RerankCrossEncoderResponse{}
	mi := &file_reranking_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankCrossEncoderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankCrossEncoderResponse) ProtoMessage() {}

func (x *RerankCrossEncoderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankCrossEncoderResponse.ProtoReflect.Descriptor instead.
func (*RerankCrossEncoderResponse) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{2}
}

func (x *RerankCrossEncoderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RerankCrossEncoderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RerankCrossEncoderResponse) GetResult() *RerankingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RerankCrossEncoderResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RerankingResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RerankedDocuments []*RetrievalResult     `protobuf:"bytes,1,rep,name=reranked_documents,json=rerankedDocuments,proto3" json:"reranked_documents,omitempty"`
	Summary           *RerankingSummary      `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RerankingResult) Reset() {
	*x = RerankingResult{}
	mi := &file_reranking_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankingResult) ProtoMessage() {}

func (x *RerankingResult) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankingResult.ProtoReflect.Descriptor instead.
func (*RerankingResult) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{3}
}

func (x *RerankingResult) GetRerankedDocuments() []*RetrievalResult {
	if x != nil {
		return x.RerankedDocuments
	}
	return nil
}

func (x *RerankingResult) GetSummary() *RerankingSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type RerankingSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RerankingMethod  string                 `protobuf:"bytes,1,opt,name=reranking_method,json=rerankingMethod,proto3" json:"reranking_method,omitempty"`
	RerankingTimeMs  float32                `protobuf:"fixed32,2,opt,name=reranking_time_ms,json=rerankingTimeMs,proto3" json:"reranking_time_ms,omitempty"`
	ImprovementScore float32                `protobuf:"fixed32,3,opt,name=improvement_score,json=improvementScore,proto3" json:"improvement_score,omitempty"`
	Metrics          []*Metric              `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RerankingSummary) Reset() {
	*x = RerankingSummary{}
	mi := &file_reranking_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankingSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankingSummary) ProtoMessage() {}

func (x *RerankingSummary) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankingSummary.ProtoReflect.Descriptor instead.
func (*RerankingSummary) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{4}
}

func (x *RerankingSummary) GetRerankingMethod() string {
	if x != nil {
		return x.RerankingMethod
	}
	return ""
}

func (x *RerankingSummary) GetRerankingTimeMs() float32 {
	if x != nil {
		return x.RerankingTimeMs
	}
	return 0
}

func (x *RerankingSummary) GetImprovementScore() float32 {
	if x != nil {
		return x.ImprovementScore
	}
	return 0
}

func (x *RerankingSummary) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metric struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Value         float32                `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_reranking_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{5}
}

func (x *Metric) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *Metric) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type RerankMonoEncoderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents      []*RetrievalResult     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	RerankingModel string                 `protobuf:"bytes,4,opt,name=reranking_model,json=rerankingModel,proto3" json:"reranking_model,omitempty"`
	TopK           int32                  `protobuf:"varint,5,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options        map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RerankMonoEncoderRequest) Reset() {
	*x = RerankMonoEncoderRequest{}
	mi := &file_reranking_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankMonoEncoderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankMonoEncoderRequest) ProtoMessage() {}

func (x *RerankMonoEncoderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankMonoEncoderRequest.ProtoReflect.Descriptor instead.
func (*RerankMonoEncoderRequest) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{6}
}

func (x *RerankMonoEncoderRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *RerankMonoEncoderRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RerankMonoEncoderRequest) GetDocuments() []*RetrievalResult {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *RerankMonoEncoderRequest) GetRerankingModel() string {
	if x != nil {
		return x.RerankingModel
	}
	return ""
}

func (x *RerankMonoEncoderRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *RerankMonoEncoderRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RerankMonoEncoderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RerankingResult       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankMonoEncoderResponse) Reset() {
	*x = RerankMonoEncoderResponse{}
	mi := &file_reranking_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankMonoEncoderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankMonoEncoderResponse) ProtoMessage() {}

func (x *RerankMonoEncoderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankMonoEncoderResponse.ProtoReflect.Descriptor instead.
func (*RerankMonoEncoderResponse) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{7}
}

func (x *RerankMonoEncoderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RerankMonoEncoderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RerankMonoEncoderResponse) GetResult() *RerankingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *RerankMonoEncoderResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CurriculumAwareRerankRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QueryId            string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query              string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents          []*RetrievalResult     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	Phase              string                 `protobuf:"bytes,4,opt,name=phase,proto3" json:"phase,omitempty"`
	Grade              string                 `protobuf:"bytes,5,opt,name=grade,proto3" json:"grade,omitempty"`
	Subject            string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	TargetCompetencies []string               `protobuf:"bytes,7,rep,name=target_competencies,json=targetCompetencies,proto3" json:"target_competencies,omitempty"`
	TopK               int32                  `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options            map[string]string      `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CurriculumAwareRerankRequest) Reset() {
	*x = CurriculumAwareRerankRequest{}
	mi := &file_reranking_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurriculumAwareRerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurriculumAwareRerankRequest) ProtoMessage() {}

func (x *CurriculumAwareRerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurriculumAwareRerankRequest.ProtoReflect.Descriptor instead.
func (*CurriculumAwareRerankRequest) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{8}
}

func (x *CurriculumAwareRerankRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *CurriculumAwareRerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CurriculumAwareRerankRequest) GetDocuments() []*RetrievalResult {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *CurriculumAwareRerankRequest) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *CurriculumAwareRerankRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *CurriculumAwareRerankRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CurriculumAwareRerankRequest) GetTargetCompetencies() []string {
	if x != nil {
		return x.TargetCompetencies
	}
	return nil
}

func (x *CurriculumAwareRerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *CurriculumAwareRerankRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CurriculumAwareRerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RerankingResult       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurriculumAwareRerankResponse) Reset() {
	*x = CurriculumAwareRerankResponse{}
	mi := &file_reranking_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurriculumAwareRerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurriculumAwareRerankResponse) ProtoMessage() {}

func (x *CurriculumAwareRerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurriculumAwareRerankResponse.ProtoReflect.Descriptor instead.
func (*CurriculumAwareRerankResponse) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{9}
}

func (x *CurriculumAwareRerankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CurriculumAwareRerankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CurriculumAwareRerankResponse) GetResult() *RerankingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CurriculumAwareRerankResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PedagogyAwareRerankRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QueryId            string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query              string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents          []*RetrievalResult     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	PedagogyType       string                 `protobuf:"bytes,4,opt,name=pedagogy_type,json=pedagogyType,proto3" json:"pedagogy_type,omitempty"`
	Grade              string                 `protobuf:"bytes,5,opt,name=grade,proto3" json:"grade,omitempty"`
	Subject            string                 `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	LearningObjectives []string               `protobuf:"bytes,7,rep,name=learning_objectives,json=learningObjectives,proto3" json:"learning_objectives,omitempty"`
	TopK               int32                  `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options            map[string]string      `protobuf:"bytes,9,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PedagogyAwareRerankRequest) Reset() {
	*x = PedagogyAwareRerankRequest{}
	mi := &file_reranking_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedagogyAwareRerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedagogyAwareRerankRequest) ProtoMessage() {}

func (x *PedagogyAwareRerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedagogyAwareRerankRequest.ProtoReflect.Descriptor instead.
func (*PedagogyAwareRerankRequest) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{10}
}

func (x *PedagogyAwareRerankRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *PedagogyAwareRerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PedagogyAwareRerankRequest) GetDocuments() []*RetrievalResult {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *PedagogyAwareRerankRequest) GetPedagogyType() string {
	if x != nil {
		return x.PedagogyType
	}
	return ""
}

func (x *PedagogyAwareRerankRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *PedagogyAwareRerankRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PedagogyAwareRerankRequest) GetLearningObjectives() []string {
	if x != nil {
		return x.LearningObjectives
	}
	return nil
}

func (x *PedagogyAwareRerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *PedagogyAwareRerankRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type PedagogyAwareRerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RerankingResult       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PedagogyAwareRerankResponse) Reset() {
	*x = PedagogyAwareRerankResponse{}
	mi := &file_reranking_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PedagogyAwareRerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PedagogyAwareRerankResponse) ProtoMessage() {}

func (x *PedagogyAwareRerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PedagogyAwareRerankResponse.ProtoReflect.Descriptor instead.
func (*PedagogyAwareRerankResponse) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{11}
}

func (x *PedagogyAwareRerankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PedagogyAwareRerankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PedagogyAwareRerankResponse) GetResult() *RerankingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PedagogyAwareRerankResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CompetencyAwareRerankRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QueryId            string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query              string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents          []*RetrievalResult     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	TargetCompetencies []string               `protobuf:"bytes,4,rep,name=target_competencies,json=targetCompetencies,proto3" json:"target_competencies,omitempty"`
	Subject            string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Grade              string                 `protobuf:"bytes,6,opt,name=grade,proto3" json:"grade,omitempty"`
	TopK               int32                  `protobuf:"varint,7,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options            map[string]string      `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CompetencyAwareRerankRequest) Reset() {
	*x = CompetencyAwareRerankRequest{}
	mi := &file_reranking_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetencyAwareRerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetencyAwareRerankRequest) ProtoMessage() {}

func (x *CompetencyAwareRerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetencyAwareRerankRequest.ProtoReflect.Descriptor instead.
func (*CompetencyAwareRerankRequest) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{12}
}

func (x *CompetencyAwareRerankRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *CompetencyAwareRerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CompetencyAwareRerankRequest) GetDocuments() []*RetrievalResult {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *CompetencyAwareRerankRequest) GetTargetCompetencies() []string {
	if x != nil {
		return x.TargetCompetencies
	}
	return nil
}

func (x *CompetencyAwareRerankRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CompetencyAwareRerankRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *CompetencyAwareRerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *CompetencyAwareRerankRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type CompetencyAwareRerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RerankingResult       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompetencyAwareRerankResponse) Reset() {
	*x = CompetencyAwareRerankResponse{}
	mi := &file_reranking_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompetencyAwareRerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompetencyAwareRerankResponse) ProtoMessage() {}

func (x *CompetencyAwareRerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompetencyAwareRerankResponse.ProtoReflect.Descriptor instead.
func (*CompetencyAwareRerankResponse) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{13}
}

func (x *CompetencyAwareRerankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompetencyAwareRerankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CompetencyAwareRerankResponse) GetResult() *RerankingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CompetencyAwareRerankResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HybridRerankRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	QueryId         string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Query           string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Documents       []*RetrievalResult     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	Strategies      []*RerankingStrategy   `protobuf:"bytes,4,rep,name=strategies,proto3" json:"strategies,omitempty"`
	StrategyWeights []float32              `protobuf:"fixed32,5,rep,packed,name=strategy_weights,json=strategyWeights,proto3" json:"strategy_weights,omitempty"`
	TopK            int32                  `protobuf:"varint,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Options         map[string]string      `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HybridRerankRequest) Reset() {
	*x = HybridRerankRequest{}
	mi := &file_reranking_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridRerankRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridRerankRequest) ProtoMessage() {}

func (x *HybridRerankRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridRerankRequest.ProtoReflect.Descriptor instead.
func (*HybridRerankRequest) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{14}
}

func (x *HybridRerankRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *HybridRerankRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HybridRerankRequest) GetDocuments() []*RetrievalResult {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *HybridRerankRequest) GetStrategies() []*RerankingStrategy {
	if x != nil {
		return x.Strategies
	}
	return nil
}

func (x *HybridRerankRequest) GetStrategyWeights() []float32 {
	if x != nil {
		return x.StrategyWeights
	}
	return nil
}

func (x *HybridRerankRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *HybridRerankRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type RerankingStrategy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StrategyName  string                 `protobuf:"bytes,1,opt,name=strategy_name,json=strategyName,proto3" json:"strategy_name,omitempty"`
	StrategyType  string                 `protobuf:"bytes,2,opt,name=strategy_type,json=strategyType,proto3" json:"strategy_type,omitempty"`
	Parameters    map[string]string      `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RerankingStrategy) Reset() {
	*x = RerankingStrategy{}
	mi := &file_reranking_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RerankingStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RerankingStrategy) ProtoMessage() {}

func (x *RerankingStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RerankingStrategy.ProtoReflect.Descriptor instead.
func (*RerankingStrategy) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{15}
}

func (x *RerankingStrategy) GetStrategyName() string {
	if x != nil {
		return x.StrategyName
	}
	return ""
}

func (x *RerankingStrategy) GetStrategyType() string {
	if x != nil {
		return x.StrategyType
	}
	return ""
}

func (x *RerankingStrategy) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type HybridRerankResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RerankingResult       `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridRerankResponse) Reset() {
	*x = HybridRerankResponse{}
	mi := &file_reranking_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridRerankResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridRerankResponse) ProtoMessage() {}

func (x *HybridRerankResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reranking_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridRerankResponse.ProtoReflect.Descriptor instead.
func (*HybridRerankResponse) Descriptor() ([]byte, []int) {
	return file_reranking_service_proto_rawDescGZIP(), []int{16}
}

func (x *HybridRerankResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HybridRerankResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HybridRerankResponse) GetResult() *RerankingResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HybridRerankResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_reranking_service_proto protoreflect.FileDescriptor

const file_reranking_service_proto_rawDesc = "" +
	"\n" +
	"\x17reranking_service.proto\x12\x1dai_platform.reranking_service\"\xf5\x02\n" +
	"\x19RerankCrossEncoderRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12L\n" +
	"\tdocuments\x18\x03 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\tdocuments\x12'\n" +
	"\x0freranking_model\x18\x04 \x01(\tR\x0ererankingModel\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12_\n" +
	"\aoptions\x18\x06 \x03(\v2E.ai_platform.reranking_service.RerankCrossEncoderRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\x0fRetrievalResult\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12X\n" +
	"\bmetadata\x18\x04 \x03(\v2<.ai_platform.reranking_service.RetrievalResult.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x02\n" +
	"\x1aRerankCrossEncoderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..ai_platform.reranking_service.RerankingResultR\x06result\x12c\n" +
	"\bmetadata\x18\x04 \x03(\v2G.ai_platform.reranking_service.RerankCrossEncoderResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\x0fRerankingResult\x12]\n" +
	"\x12reranked_documents\x18\x01 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\x11rerankedDocuments\x12I\n" +
	"\asummary\x18\x02 \x01(\v2/.ai_platform.reranking_service.RerankingSummaryR\asummary\"\xd7\x01\n" +
	"\x10RerankingSummary\x12)\n" +
	"\x10reranking_method\x18\x01 \x01(\tR\x0frerankingMethod\x12*\n" +
	"\x11reranking_time_ms\x18\x02 \x01(\x02R\x0frerankingTimeMs\x12+\n" +
	"\x11improvement_score\x18\x03 \x01(\x02R\x10improvementScore\x12?\n" +
	"\ametrics\x18\x04 \x03(\v2%.ai_platform.reranking_service.MetricR\ametrics\"?\n" +
	"\x06Metric\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value\"\xf3\x02\n" +
	"\x18RerankMonoEncoderRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12L\n" +
	"\tdocuments\x18\x03 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\tdocuments\x12'\n" +
	"\x0freranking_model\x18\x04 \x01(\tR\x0ererankingModel\x12\x13\n" +
	"\x05top_k\x18\x05 \x01(\x05R\x04topK\x12^\n" +
	"\aoptions\x18\x06 \x03(\v2D.ai_platform.reranking_service.RerankMonoEncoderRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb8\x02\n" +
	"\x19RerankMonoEncoderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..ai_platform.reranking_service.RerankingResultR\x06result\x12b\n" +
	"\bmetadata\x18\x04 \x03(\v2F.ai_platform.reranking_service.RerankMonoEncoderResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc9\x03\n" +
	"\x1cCurriculumAwareRerankRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12L\n" +
	"\tdocuments\x18\x03 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\tdocuments\x12\x14\n" +
	"\x05phase\x18\x04 \x01(\tR\x05phase\x12\x14\n" +
	"\x05grade\x18\x05 \x01(\tR\x05grade\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12/\n" +
	"\x13target_competencies\x18\a \x03(\tR\x12targetCompetencies\x12\x13\n" +
	"\x05top_k\x18\b \x01(\x05R\x04topK\x12b\n" +
	"\aoptions\x18\t \x03(\v2H.ai_platform.reranking_service.CurriculumAwareRerankRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x02\n" +
	"\x1dCurriculumAwareRerankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..ai_platform.reranking_service.RerankingResultR\x06result\x12f\n" +
	"\bmetadata\x18\x04 \x03(\v2J.ai_platform.reranking_service.CurriculumAwareRerankResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd4\x03\n" +
	"\x1aPedagogyAwareRerankRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12L\n" +
	"\tdocuments\x18\x03 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\tdocuments\x12#\n" +
	"\rpedagogy_type\x18\x04 \x01(\tR\fpedagogyType\x12\x14\n" +
	"\x05grade\x18\x05 \x01(\tR\x05grade\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12/\n" +
	"\x13learning_objectives\x18\a \x03(\tR\x12learningObjectives\x12\x13\n" +
	"\x05top_k\x18\b \x01(\x05R\x04topK\x12`\n" +
	"\aoptions\x18\t \x03(\v2F.ai_platform.reranking_service.PedagogyAwareRerankRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x02\n" +
	"\x1bPedagogyAwareRerankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..ai_platform.reranking_service.RerankingResultR\x06result\x12d\n" +
	"\bmetadata\x18\x04 \x03(\v2H.ai_platform.reranking_service.PedagogyAwareRerankResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x03\n" +
	"\x1cCompetencyAwareRerankRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12L\n" +
	"\tdocuments\x18\x03 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\tdocuments\x12/\n" +
	"\x13target_competencies\x18\x04 \x03(\tR\x12targetCompetencies\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x14\n" +
	"\x05grade\x18\x06 \x01(\tR\x05grade\x12\x13\n" +
	"\x05top_k\x18\a \x01(\x05R\x04topK\x12b\n" +
	"\aoptions\x18\b \x03(\v2H.ai_platform.reranking_service.CompetencyAwareRerankRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x02\n" +
	"\x1dCompetencyAwareRerankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..ai_platform.reranking_service.RerankingResultR\x06result\x12f\n" +
	"\bmetadata\x18\x04 \x03(\v2J.ai_platform.reranking_service.CompetencyAwareRerankResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x03\n" +
	"\x13HybridRerankRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12L\n" +
	"\tdocuments\x18\x03 \x03(\v2..ai_platform.reranking_service.RetrievalResultR\tdocuments\x12P\n" +
	"\n" +
	"strategies\x18\x04 \x03(\v20.ai_platform.reranking_service.RerankingStrategyR\n" +
	"strategies\x12)\n" +
	"\x10strategy_weights\x18\x05 \x03(\x02R\x0fstrategyWeights\x12\x13\n" +
	"\x05top_k\x18\x06 \x01(\x05R\x04topK\x12Y\n" +
	"\aoptions\x18\a \x03(\v2?.ai_platform.reranking_service.HybridRerankRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x01\n" +
	"\x11RerankingStrategy\x12#\n" +
	"\rstrategy_name\x18\x01 \x01(\tR\fstrategyName\x12#\n" +
	"\rstrategy_type\x18\x02 \x01(\tR\fstrategyType\x12`\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2@.ai_platform.reranking_service.RerankingStrategy.ParametersEntryR\n" +
	"parameters\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x02\n" +
	"\x14HybridRerankResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12F\n" +
	"\x06result\x18\x03 \x01(\v2..ai_platform.reranking_service.RerankingResultR\x06result\x12]\n" +
	"\bmetadata\x18\x04 \x03(\v2A.ai_platform.reranking_service.HybridRerankResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd9\x06\n" +
	"\x10RerankingService\x12\x89\x01\n" +
	"\x12RerankCrossEncoder\x128.ai_platform.reranking_service.RerankCrossEncoderRequest\x1a9.ai_platform.reranking_service.RerankCrossEncoderResponse\x12\x86\x01\n" +
	"\x11RerankMonoEncoder\x127.ai_platform.reranking_service.RerankMonoEncoderRequest\x1a8.ai_platform.reranking_service.RerankMonoEncoderResponse\x12\x92\x01\n" +
	"\x15CurriculumAwareRerank\x12;.ai_platform.reranking_service.CurriculumAwareRerankRequest\x1a<.ai_platform.reranking_service.CurriculumAwareRerankResponse\x12\x8c\x01\n" +
	"\x13PedagogyAwareRerank\x129.ai_platform.reranking_service.PedagogyAwareRerankRequest\x1a:.ai_platform.reranking_service.PedagogyAwareRerankResponse\x12\x92\x01\n" +
	"\x15CompetencyAwareRerank\x12;.ai_platform.reranking_service.CompetencyAwareRerankRequest\x1a<.ai_platform.reranking_service.CompetencyAwareRerankResponse\x12w\n" +
	"\fHybridRerank\x122.ai_platform.reranking_service.HybridRerankRequest\x1a3.ai_platform.reranking_service.HybridRerankResponseB2Z0sim-sekolah/internal/ai/grpc/pb/rerankingserviceb\x06proto3"

var (
	file_reranking_service_proto_rawDescOnce sync.Once
	file_reranking_service_proto_rawDescData []byte
)

func file_reranking_service_proto_rawDescGZIP() []byte {
	file_reranking_service_proto_rawDescOnce.Do(func() {
		file_reranking_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reranking_service_proto_rawDesc), len(file_reranking_service_proto_rawDesc)))
	})
	return file_reranking_service_proto_rawDescData
}

var file_reranking_service_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_reranking_service_proto_goTypes = []any{
	(*RerankCrossEncoderRequest)(nil),     // 0: ai_platform.reranking_service.RerankCrossEncoderRequest
	(*RetrievalResult)(nil),               // 1: ai_platform.reranking_service.RetrievalResult
	(*RerankCrossEncoderResponse)(nil),    // 2: ai_platform.reranking_service.RerankCrossEncoderResponse
	(*RerankingResult)(nil),               // 3: ai_platform.reranking_service.RerankingResult
	(*RerankingSummary)(nil),              // 4: ai_platform.reranking_service.RerankingSummary
	(*Metric)(nil),                        // 5: ai_platform.reranking_service.Metric
	(*RerankMonoEncoderRequest)(nil),      // 6: ai_platform.reranking_service.RerankMonoEncoderRequest
	(*RerankMonoEncoderResponse)(nil),     // 7: ai_platform.reranking_service.RerankMonoEncoderResponse
	(*CurriculumAwareRerankRequest)(nil),  // 8: ai_platform.reranking_service.CurriculumAwareRerankRequest
	(*CurriculumAwareRerankResponse)(nil), // 9: ai_platform.reranking_service.CurriculumAwareRerankResponse
	(*PedagogyAwareRerankRequest)(nil),    // 10: ai_platform.reranking_service.PedagogyAwareRerankRequest
	(*PedagogyAwareRerankResponse)(nil),   // 11: ai_platform.reranking_service.PedagogyAwareRerankResponse
	(*CompetencyAwareRerankRequest)(nil),  // 12: ai_platform.reranking_service.CompetencyAwareRerankRequest
	(*CompetencyAwareRerankResponse)(nil), // 13: ai_platform.reranking_service.CompetencyAwareRerankResponse
	(*HybridRerankRequest)(nil),           // 14: ai_platform.reranking_service.HybridRerankRequest
	(*RerankingStrategy)(nil),             // 15: ai_platform.reranking_service.RerankingStrategy
	(*HybridRerankResponse)(nil),          // 16: ai_platform.reranking_service.HybridRerankResponse
	nil,                                   // 17: ai_platform.reranking_service.RerankCrossEncoderRequest.OptionsEntry
	nil,                                   // 18: ai_platform.reranking_service.RetrievalResult.MetadataEntry
	nil,                                   // 19: ai_platform.reranking_service.RerankCrossEncoderResponse.MetadataEntry
	nil,                                   // 20: ai_platform.reranking_service.RerankMonoEncoderRequest.OptionsEntry
	nil,                                   // 21: ai_platform.reranking_service.RerankMonoEncoderResponse.MetadataEntry
	nil,                                   // 22: ai_platform.reranking_service.CurriculumAwareRerankRequest.OptionsEntry
	nil,                                   // 23: ai_platform.reranking_service.CurriculumAwareRerankResponse.MetadataEntry
	nil,                                   // 24: ai_platform.reranking_service.PedagogyAwareRerankRequest.OptionsEntry
	nil,                                   // 25: ai_platform.reranking_service.PedagogyAwareRerankResponse.MetadataEntry
	nil,                                   // 26: ai_platform.reranking_service.CompetencyAwareRerankRequest.OptionsEntry
	nil,                                   // 27: ai_platform.reranking_service.CompetencyAwareRerankResponse.MetadataEntry
	nil,                                   // 28: ai_platform.reranking_service.HybridRerankRequest.OptionsEntry
	nil,                                   // 29: ai_platform.reranking_service.RerankingStrategy.ParametersEntry
	nil,                                   // 30: ai_platform.reranking_service.HybridRerankResponse.MetadataEntry
}
var file_reranking_service_proto_depIdxs = []int32{
	1,  // 0: ai_platform.reranking_service.RerankCrossEncoderRequest.documents:type_name -> ai_platform.reranking_service.RetrievalResult
	17, // 1: ai_platform.reranking_service.RerankCrossEncoderRequest.options:type_name -> ai_platform.reranking_service.RerankCrossEncoderRequest.OptionsEntry
	18, // 2: ai_platform.reranking_service.RetrievalResult.metadata:type_name -> ai_platform.reranking_service.RetrievalResult.MetadataEntry
	3,  // 3: ai_platform.reranking_service.RerankCrossEncoderResponse.result:type_name -> ai_platform.reranking_service.RerankingResult
	19, // 4: ai_platform.reranking_service.RerankCrossEncoderResponse.metadata:type_name -> ai_platform.reranking_service.RerankCrossEncoderResponse.MetadataEntry
	1,  // 5: ai_platform.reranking_service.RerankingResult.reranked_documents:type_name -> ai_platform.reranking_service.RetrievalResult
	4,  // 6: ai_platform.reranking_service.RerankingResult.summary:type_name -> ai_platform.reranking_service.RerankingSummary
	5,  // 7: ai_platform.reranking_service.RerankingSummary.metrics:type_name -> ai_platform.reranking_service.Metric
	1,  // 8: ai_platform.reranking_service.RerankMonoEncoderRequest.documents:type_name -> ai_platform.reranking_service.RetrievalResult
	20, // 9: ai_platform.reranking_service.RerankMonoEncoderRequest.options:type_name -> ai_platform.reranking_service.RerankMonoEncoderRequest.OptionsEntry
	3,  // 10: ai_platform.reranking_service.RerankMonoEncoderResponse.result:type_name -> ai_platform.reranking_service.RerankingResult
	21, // 11: ai_platform.reranking_service.RerankMonoEncoderResponse.metadata:type_name -> ai_platform.reranking_service.RerankMonoEncoderResponse.MetadataEntry
	1,  // 12: ai_platform.reranking_service.CurriculumAwareRerankRequest.documents:type_name -> ai_platform.reranking_service.RetrievalResult
	22, // 13: ai_platform.reranking_service.CurriculumAwareRerankRequest.options:type_name -> ai_platform.reranking_service.CurriculumAwareRerankRequest.OptionsEntry
	3,  // 14: ai_platform.reranking_service.CurriculumAwareRerankResponse.result:type_name -> ai_platform.reranking_service.RerankingResult
	23, // 15: ai_platform.reranking_service.CurriculumAwareRerankResponse.metadata:type_name -> ai_platform.reranking_service.CurriculumAwareRerankResponse.MetadataEntry
	1,  // 16: ai_platform.reranking_service.PedagogyAwareRerankRequest.documents:type_name -> ai_platform.reranking_service.RetrievalResult
	24, // 17: ai_platform.reranking_service.PedagogyAwareRerankRequest.options:type_name -> ai_platform.reranking_service.PedagogyAwareRerankRequest.OptionsEntry
	3,  // 18: ai_platform.reranking_service.PedagogyAwareRerankResponse.result:type_name -> ai_platform.reranking_service.RerankingResult
	25, // 19: ai_platform.reranking_service.PedagogyAwareRerankResponse.metadata:type_name -> ai_platform.reranking_service.PedagogyAwareRerankResponse.MetadataEntry
	1,  // 20: ai_platform.reranking_service.CompetencyAwareRerankRequest.documents:type_name -> ai_platform.reranking_service.RetrievalResult
	26, // 21: ai_platform.reranking_service.CompetencyAwareRerankRequest.options:type_name -> ai_platform.reranking_service.CompetencyAwareRerankRequest.OptionsEntry
	3,  // 22: ai_platform.reranking_service.CompetencyAwareRerankResponse.result:type_name -> ai_platform.reranking_service.RerankingResult
	27, // 23: ai_platform.reranking_service.CompetencyAwareRerankResponse.metadata:type_name -> ai_platform.reranking_service.CompetencyAwareRerankResponse.MetadataEntry
	1,  // 24: ai_platform.reranking_service.HybridRerankRequest.documents:type_name -> ai_platform.reranking_service.RetrievalResult
	15, // 25: ai_platform.reranking_service.HybridRerankRequest.strategies:type_name -> ai_platform.reranking_service.RerankingStrategy
	28, // 26: ai_platform.reranking_service.HybridRerankRequest.options:type_name -> ai_platform.reranking_service.HybridRerankRequest.OptionsEntry
	29, // 27: ai_platform.reranking_service.RerankingStrategy.parameters:type_name -> ai_platform.reranking_service.RerankingStrategy.ParametersEntry
	3,  // 28: ai_platform.reranking_service.HybridRerankResponse.result:type_name -> ai_platform.reranking_service.RerankingResult
	30, // 29: ai_platform.reranking_service.HybridRerankResponse.metadata:type_name -> ai_platform.reranking_service.HybridRerankResponse.MetadataEntry
	0,  // 30: ai_platform.reranking_service.RerankingService.RerankCrossEncoder:input_type -> ai_platform.reranking_service.RerankCrossEncoderRequest
	6,  // 31: ai_platform.reranking_service.RerankingService.RerankMonoEncoder:input_type -> ai_platform.reranking_service.RerankMonoEncoderRequest
	8,  // 32: ai_platform.reranking_service.RerankingService.CurriculumAwareRerank:input_type -> ai_platform.reranking_service.CurriculumAwareRerankRequest
	10, // 33: ai_platform.reranking_service.RerankingService.PedagogyAwareRerank:input_type -> ai_platform.reranking_service.PedagogyAwareRerankRequest
	12, // 34: ai_platform.reranking_service.RerankingService.CompetencyAwareRerank:input_type -> ai_platform.reranking_service.CompetencyAwareRerankRequest
	14, // 35: ai_platform.reranking_service.RerankingService.HybridRerank:input_type -> ai_platform.reranking_service.HybridRerankRequest
	2,  // 36: ai_platform.reranking_service.RerankingService.RerankCrossEncoder:output_type -> ai_platform.reranking_service.RerankCrossEncoderResponse
	7,  // 37: ai_platform.reranking_service.RerankingService.RerankMonoEncoder:output_type -> ai_platform.reranking_service.RerankMonoEncoderResponse
	9,  // 38: ai_platform.reranking_service.RerankingService.CurriculumAwareRerank:output_type -> ai_platform.reranking_service.CurriculumAwareRerankResponse
	11, // 39: ai_platform.reranking_service.RerankingService.PedagogyAwareRerank:output_type -> ai_platform.reranking_service.PedagogyAwareRerankResponse
	13, // 40: ai_platform.reranking_service.RerankingService.CompetencyAwareRerank:output_type -> ai_platform.reranking_service.CompetencyAwareRerankResponse
	16, // 41: ai_platform.reranking_service.RerankingService.HybridRerank:output_type -> ai_platform.reranking_service.HybridRerankResponse
	36, // [36:42] is the sub-list for method output_type
	30, // [30:36] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_reranking_service_proto_init() }
func file_reranking_service_proto_init() {
	if File_reranking_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reranking_service_proto_rawDesc), len(file_reranking_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reranking_service_proto_goTypes,
		DependencyIndexes: file_reranking_service_proto_depIdxs,
		MessageInfos:      file_reranking_service_proto_msgTypes,
	}.Build()
	File_reranking_service_proto = out.File
	file_reranking_service_proto_goTypes = nil
	file_reranking_service_proto_depIdxs = nil
}
