# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import embedding_service_pb2 as embedding__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in embedding_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """Embedding Service - Fase 3.1
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EmbedText = channel.unary_unary(
                '/ai_platform.embedding_service.EmbeddingService/EmbedText',
                request_serializer=embedding__service__pb2.EmbedTextRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.EmbedTextResponse.FromString,
                _registered_method=True)
        self.EmbedImage = channel.unary_unary(
                '/ai_platform.embedding_service.EmbeddingService/EmbedImage',
                request_serializer=embedding__service__pb2.EmbedImageRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.EmbedImageResponse.FromString,
                _registered_method=True)
        self.EmbedTable = channel.unary_unary(
                '/ai_platform.embedding_service.EmbeddingService/EmbedTable',
                request_serializer=embedding__service__pb2.EmbedTableRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.EmbedTableResponse.FromString,
                _registered_method=True)
        self.EmbedFormula = channel.unary_unary(
                '/ai_platform.embedding_service.EmbeddingService/EmbedFormula',
                request_serializer=embedding__service__pb2.EmbedFormulaRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.EmbedFormulaResponse.FromString,
                _registered_method=True)
        self.BatchEmbedText = channel.unary_unary(
                '/ai_platform.embedding_service.EmbeddingService/BatchEmbedText',
                request_serializer=embedding__service__pb2.BatchEmbedTextRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.BatchEmbedTextResponse.FromString,
                _registered_method=True)
        self.GetEmbeddingInfo = channel.unary_unary(
                '/ai_platform.embedding_service.EmbeddingService/GetEmbeddingInfo',
                request_serializer=embedding__service__pb2.GetEmbeddingInfoRequest.SerializeToString,
                response_deserializer=embedding__service__pb2.GetEmbeddingInfoResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """Embedding Service - Fase 3.1
    """

    def EmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedFormula(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchEmbedText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbeddingInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedText,
                    request_deserializer=embedding__service__pb2.EmbedTextRequest.FromString,
                    response_serializer=embedding__service__pb2.EmbedTextResponse.SerializeToString,
            ),
            'EmbedImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedImage,
                    request_deserializer=embedding__service__pb2.EmbedImageRequest.FromString,
                    response_serializer=embedding__service__pb2.EmbedImageResponse.SerializeToString,
            ),
            'EmbedTable': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedTable,
                    request_deserializer=embedding__service__pb2.EmbedTableRequest.FromString,
                    response_serializer=embedding__service__pb2.EmbedTableResponse.SerializeToString,
            ),
            'EmbedFormula': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedFormula,
                    request_deserializer=embedding__service__pb2.EmbedFormulaRequest.FromString,
                    response_serializer=embedding__service__pb2.EmbedFormulaResponse.SerializeToString,
            ),
            'BatchEmbedText': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchEmbedText,
                    request_deserializer=embedding__service__pb2.BatchEmbedTextRequest.FromString,
                    response_serializer=embedding__service__pb2.BatchEmbedTextResponse.SerializeToString,
            ),
            'GetEmbeddingInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeddingInfo,
                    request_deserializer=embedding__service__pb2.GetEmbeddingInfoRequest.FromString,
                    response_serializer=embedding__service__pb2.GetEmbeddingInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.embedding_service.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.embedding_service.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Embedding Service - Fase 3.1
    """

    @staticmethod
    def EmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.embedding_service.EmbeddingService/EmbedText',
            embedding__service__pb2.EmbedTextRequest.SerializeToString,
            embedding__service__pb2.EmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.embedding_service.EmbeddingService/EmbedImage',
            embedding__service__pb2.EmbedImageRequest.SerializeToString,
            embedding__service__pb2.EmbedImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.embedding_service.EmbeddingService/EmbedTable',
            embedding__service__pb2.EmbedTableRequest.SerializeToString,
            embedding__service__pb2.EmbedTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmbedFormula(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.embedding_service.EmbeddingService/EmbedFormula',
            embedding__service__pb2.EmbedFormulaRequest.SerializeToString,
            embedding__service__pb2.EmbedFormulaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchEmbedText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.embedding_service.EmbeddingService/BatchEmbedText',
            embedding__service__pb2.BatchEmbedTextRequest.SerializeToString,
            embedding__service__pb2.BatchEmbedTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbeddingInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.embedding_service.EmbeddingService/GetEmbeddingInfo',
            embedding__service__pb2.GetEmbeddingInfoRequest.SerializeToString,
            embedding__service__pb2.GetEmbeddingInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
