# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import retrieval_service_pb2 as retrieval__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retrieval_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalServiceStub(object):
    """Retrieval Service - Fase 3.2
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SemanticSearch = channel.unary_unary(
                '/ai_platform.retrieval_service.RetrievalService/SemanticSearch',
                request_serializer=retrieval__service__pb2.SemanticSearchRequest.SerializeToString,
                response_deserializer=retrieval__service__pb2.SemanticSearchResponse.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_unary(
                '/ai_platform.retrieval_service.RetrievalService/HybridSearch',
                request_serializer=retrieval__service__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=retrieval__service__pb2.HybridSearchResponse.FromString,
                _registered_method=True)
        self.FilterByMetadata = channel.unary_unary(
                '/ai_platform.retrieval_service.RetrievalService/FilterByMetadata',
                request_serializer=retrieval__service__pb2.FilterByMetadataRequest.SerializeToString,
                response_deserializer=retrieval__service__pb2.FilterByMetadataResponse.FromString,
                _registered_method=True)
        self.BuildContext = channel.unary_unary(
                '/ai_platform.retrieval_service.RetrievalService/BuildContext',
                request_serializer=retrieval__service__pb2.BuildContextRequest.SerializeToString,
                response_deserializer=retrieval__service__pb2.BuildContextResponse.FromString,
                _registered_method=True)
        self.ExpandQuery = channel.unary_unary(
                '/ai_platform.retrieval_service.RetrievalService/ExpandQuery',
                request_serializer=retrieval__service__pb2.ExpandQueryRequest.SerializeToString,
                response_deserializer=retrieval__service__pb2.ExpandQueryResponse.FromString,
                _registered_method=True)
        self.GetRelevanceScores = channel.unary_unary(
                '/ai_platform.retrieval_service.RetrievalService/GetRelevanceScores',
                request_serializer=retrieval__service__pb2.GetRelevanceScoresRequest.SerializeToString,
                response_deserializer=retrieval__service__pb2.GetRelevanceScoresResponse.FromString,
                _registered_method=True)


class RetrievalServiceServicer(object):
    """Retrieval Service - Fase 3.2
    """

    def SemanticSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FilterByMetadata(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelevanceScores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SemanticSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.SemanticSearch,
                    request_deserializer=retrieval__service__pb2.SemanticSearchRequest.FromString,
                    response_serializer=retrieval__service__pb2.SemanticSearchResponse.SerializeToString,
            ),
            'HybridSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=retrieval__service__pb2.HybridSearchRequest.FromString,
                    response_serializer=retrieval__service__pb2.HybridSearchResponse.SerializeToString,
            ),
            'FilterByMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.FilterByMetadata,
                    request_deserializer=retrieval__service__pb2.FilterByMetadataRequest.FromString,
                    response_serializer=retrieval__service__pb2.FilterByMetadataResponse.SerializeToString,
            ),
            'BuildContext': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildContext,
                    request_deserializer=retrieval__service__pb2.BuildContextRequest.FromString,
                    response_serializer=retrieval__service__pb2.BuildContextResponse.SerializeToString,
            ),
            'ExpandQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandQuery,
                    request_deserializer=retrieval__service__pb2.ExpandQueryRequest.FromString,
                    response_serializer=retrieval__service__pb2.ExpandQueryResponse.SerializeToString,
            ),
            'GetRelevanceScores': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelevanceScores,
                    request_deserializer=retrieval__service__pb2.GetRelevanceScoresRequest.FromString,
                    response_serializer=retrieval__service__pb2.GetRelevanceScoresResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.retrieval_service.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.retrieval_service.RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """Retrieval Service - Fase 3.2
    """

    @staticmethod
    def SemanticSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.retrieval_service.RetrievalService/SemanticSearch',
            retrieval__service__pb2.SemanticSearchRequest.SerializeToString,
            retrieval__service__pb2.SemanticSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.retrieval_service.RetrievalService/HybridSearch',
            retrieval__service__pb2.HybridSearchRequest.SerializeToString,
            retrieval__service__pb2.HybridSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FilterByMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.retrieval_service.RetrievalService/FilterByMetadata',
            retrieval__service__pb2.FilterByMetadataRequest.SerializeToString,
            retrieval__service__pb2.FilterByMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.retrieval_service.RetrievalService/BuildContext',
            retrieval__service__pb2.BuildContextRequest.SerializeToString,
            retrieval__service__pb2.BuildContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.retrieval_service.RetrievalService/ExpandQuery',
            retrieval__service__pb2.ExpandQueryRequest.SerializeToString,
            retrieval__service__pb2.ExpandQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelevanceScores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.retrieval_service.RetrievalService/GetRelevanceScores',
            retrieval__service__pb2.GetRelevanceScoresRequest.SerializeToString,
            retrieval__service__pb2.GetRelevanceScoresResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
