# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import educational_intelligence_pb2 as educational__intelligence__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in educational_intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdaptiveLearningEngineStub(object):
    """Educational Intelligence Services - Fase 5
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePersonalizedLearningPath = channel.unary_unary(
                '/ai_platform.educational_intelligence.AdaptiveLearningEngine/GeneratePersonalizedLearningPath',
                request_serializer=educational__intelligence__pb2.PersonalizedLearningRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.LearningPathResponse.FromString,
                _registered_method=True)
        self.AnalyzeStudentLearningPattern = channel.unary_unary(
                '/ai_platform.educational_intelligence.AdaptiveLearningEngine/AnalyzeStudentLearningPattern',
                request_serializer=educational__intelligence__pb2.LearningPatternRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.PatternAnalysisResponse.FromString,
                _registered_method=True)


class AdaptiveLearningEngineServicer(object):
    """Educational Intelligence Services - Fase 5
    """

    def GeneratePersonalizedLearningPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeStudentLearningPattern(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdaptiveLearningEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePersonalizedLearningPath': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePersonalizedLearningPath,
                    request_deserializer=educational__intelligence__pb2.PersonalizedLearningRequest.FromString,
                    response_serializer=educational__intelligence__pb2.LearningPathResponse.SerializeToString,
            ),
            'AnalyzeStudentLearningPattern': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeStudentLearningPattern,
                    request_deserializer=educational__intelligence__pb2.LearningPatternRequest.FromString,
                    response_serializer=educational__intelligence__pb2.PatternAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.AdaptiveLearningEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.AdaptiveLearningEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdaptiveLearningEngine(object):
    """Educational Intelligence Services - Fase 5
    """

    @staticmethod
    def GeneratePersonalizedLearningPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.AdaptiveLearningEngine/GeneratePersonalizedLearningPath',
            educational__intelligence__pb2.PersonalizedLearningRequest.SerializeToString,
            educational__intelligence__pb2.LearningPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeStudentLearningPattern(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.AdaptiveLearningEngine/AnalyzeStudentLearningPattern',
            educational__intelligence__pb2.LearningPatternRequest.SerializeToString,
            educational__intelligence__pb2.PatternAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AssessmentEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateAdaptiveAssessment = channel.unary_unary(
                '/ai_platform.educational_intelligence.AssessmentEngine/GenerateAdaptiveAssessment',
                request_serializer=educational__intelligence__pb2.AdaptiveAssessmentRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.AdaptiveAssessmentResponse.FromString,
                _registered_method=True)
        self.AnalyzeAssessmentResults = channel.unary_unary(
                '/ai_platform.educational_intelligence.AssessmentEngine/AnalyzeAssessmentResults',
                request_serializer=educational__intelligence__pb2.AssessmentAnalysisRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.AssessmentAnalysisResponse.FromString,
                _registered_method=True)


class AssessmentEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateAdaptiveAssessment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAssessmentResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssessmentEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateAdaptiveAssessment': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateAdaptiveAssessment,
                    request_deserializer=educational__intelligence__pb2.AdaptiveAssessmentRequest.FromString,
                    response_serializer=educational__intelligence__pb2.AdaptiveAssessmentResponse.SerializeToString,
            ),
            'AnalyzeAssessmentResults': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAssessmentResults,
                    request_deserializer=educational__intelligence__pb2.AssessmentAnalysisRequest.FromString,
                    response_serializer=educational__intelligence__pb2.AssessmentAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.AssessmentEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.AssessmentEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssessmentEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateAdaptiveAssessment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.AssessmentEngine/GenerateAdaptiveAssessment',
            educational__intelligence__pb2.AdaptiveAssessmentRequest.SerializeToString,
            educational__intelligence__pb2.AdaptiveAssessmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeAssessmentResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.AssessmentEngine/AnalyzeAssessmentResults',
            educational__intelligence__pb2.AssessmentAnalysisRequest.SerializeToString,
            educational__intelligence__pb2.AssessmentAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CurriculumEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateCurriculumPlan = channel.unary_unary(
                '/ai_platform.educational_intelligence.CurriculumEngine/GenerateCurriculumPlan',
                request_serializer=educational__intelligence__pb2.CurriculumPlanRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.CurriculumPlanResponse.FromString,
                _registered_method=True)
        self.AlignContentWithStandards = channel.unary_unary(
                '/ai_platform.educational_intelligence.CurriculumEngine/AlignContentWithStandards',
                request_serializer=educational__intelligence__pb2.ContentAlignmentRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.AlignmentResponse.FromString,
                _registered_method=True)


class CurriculumEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateCurriculumPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AlignContentWithStandards(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CurriculumEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateCurriculumPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCurriculumPlan,
                    request_deserializer=educational__intelligence__pb2.CurriculumPlanRequest.FromString,
                    response_serializer=educational__intelligence__pb2.CurriculumPlanResponse.SerializeToString,
            ),
            'AlignContentWithStandards': grpc.unary_unary_rpc_method_handler(
                    servicer.AlignContentWithStandards,
                    request_deserializer=educational__intelligence__pb2.ContentAlignmentRequest.FromString,
                    response_serializer=educational__intelligence__pb2.AlignmentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.CurriculumEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.CurriculumEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CurriculumEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateCurriculumPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.CurriculumEngine/GenerateCurriculumPlan',
            educational__intelligence__pb2.CurriculumPlanRequest.SerializeToString,
            educational__intelligence__pb2.CurriculumPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AlignContentWithStandards(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.CurriculumEngine/AlignContentWithStandards',
            educational__intelligence__pb2.ContentAlignmentRequest.SerializeToString,
            educational__intelligence__pb2.AlignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LearningGraphEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildLearningGraph = channel.unary_unary(
                '/ai_platform.educational_intelligence.LearningGraphEngine/BuildLearningGraph',
                request_serializer=educational__intelligence__pb2.LearningGraphRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.LearningGraphResponse.FromString,
                _registered_method=True)
        self.AnalyzeLearningPath = channel.unary_unary(
                '/ai_platform.educational_intelligence.LearningGraphEngine/AnalyzeLearningPath',
                request_serializer=educational__intelligence__pb2.LearningPathAnalysisRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.PathAnalysisResponse.FromString,
                _registered_method=True)


class LearningGraphEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuildLearningGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeLearningPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearningGraphEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildLearningGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildLearningGraph,
                    request_deserializer=educational__intelligence__pb2.LearningGraphRequest.FromString,
                    response_serializer=educational__intelligence__pb2.LearningGraphResponse.SerializeToString,
            ),
            'AnalyzeLearningPath': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeLearningPath,
                    request_deserializer=educational__intelligence__pb2.LearningPathAnalysisRequest.FromString,
                    response_serializer=educational__intelligence__pb2.PathAnalysisResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.LearningGraphEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.LearningGraphEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearningGraphEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuildLearningGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.LearningGraphEngine/BuildLearningGraph',
            educational__intelligence__pb2.LearningGraphRequest.SerializeToString,
            educational__intelligence__pb2.LearningGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeLearningPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.LearningGraphEngine/AnalyzeLearningPath',
            educational__intelligence__pb2.LearningPathAnalysisRequest.SerializeToString,
            educational__intelligence__pb2.PathAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class LearningProgressionEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TrackStudentProgression = channel.unary_unary(
                '/ai_platform.educational_intelligence.LearningProgressionEngine/TrackStudentProgression',
                request_serializer=educational__intelligence__pb2.ProgressionTrackingRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.ProgressionResponse.FromString,
                _registered_method=True)
        self.PredictLearningOutcomes = channel.unary_unary(
                '/ai_platform.educational_intelligence.LearningProgressionEngine/PredictLearningOutcomes',
                request_serializer=educational__intelligence__pb2.LearningOutcomesRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.OutcomesResponse.FromString,
                _registered_method=True)


class LearningProgressionEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TrackStudentProgression(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictLearningOutcomes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearningProgressionEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TrackStudentProgression': grpc.unary_unary_rpc_method_handler(
                    servicer.TrackStudentProgression,
                    request_deserializer=educational__intelligence__pb2.ProgressionTrackingRequest.FromString,
                    response_serializer=educational__intelligence__pb2.ProgressionResponse.SerializeToString,
            ),
            'PredictLearningOutcomes': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictLearningOutcomes,
                    request_deserializer=educational__intelligence__pb2.LearningOutcomesRequest.FromString,
                    response_serializer=educational__intelligence__pb2.OutcomesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.LearningProgressionEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.LearningProgressionEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LearningProgressionEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TrackStudentProgression(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.LearningProgressionEngine/TrackStudentProgression',
            educational__intelligence__pb2.ProgressionTrackingRequest.SerializeToString,
            educational__intelligence__pb2.ProgressionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictLearningOutcomes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.LearningProgressionEngine/PredictLearningOutcomes',
            educational__intelligence__pb2.LearningOutcomesRequest.SerializeToString,
            educational__intelligence__pb2.OutcomesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PedagogyEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecommendPedagogyStrategy = channel.unary_unary(
                '/ai_platform.educational_intelligence.PedagogyEngine/RecommendPedagogyStrategy',
                request_serializer=educational__intelligence__pb2.PedagogyRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.PedagogyResponse.FromString,
                _registered_method=True)
        self.EvaluateTeachingEffectiveness = channel.unary_unary(
                '/ai_platform.educational_intelligence.PedagogyEngine/EvaluateTeachingEffectiveness',
                request_serializer=educational__intelligence__pb2.EffectivenessEvaluationRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.EffectivenessResponse.FromString,
                _registered_method=True)


class PedagogyEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecommendPedagogyStrategy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvaluateTeachingEffectiveness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PedagogyEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecommendPedagogyStrategy': grpc.unary_unary_rpc_method_handler(
                    servicer.RecommendPedagogyStrategy,
                    request_deserializer=educational__intelligence__pb2.PedagogyRequest.FromString,
                    response_serializer=educational__intelligence__pb2.PedagogyResponse.SerializeToString,
            ),
            'EvaluateTeachingEffectiveness': grpc.unary_unary_rpc_method_handler(
                    servicer.EvaluateTeachingEffectiveness,
                    request_deserializer=educational__intelligence__pb2.EffectivenessEvaluationRequest.FromString,
                    response_serializer=educational__intelligence__pb2.EffectivenessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.PedagogyEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.PedagogyEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PedagogyEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecommendPedagogyStrategy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.PedagogyEngine/RecommendPedagogyStrategy',
            educational__intelligence__pb2.PedagogyRequest.SerializeToString,
            educational__intelligence__pb2.PedagogyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvaluateTeachingEffectiveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.PedagogyEngine/EvaluateTeachingEffectiveness',
            educational__intelligence__pb2.EffectivenessEvaluationRequest.SerializeToString,
            educational__intelligence__pb2.EffectivenessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecommendationEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateContentRecommendations = channel.unary_unary(
                '/ai_platform.educational_intelligence.RecommendationEngine/GenerateContentRecommendations',
                request_serializer=educational__intelligence__pb2.ContentRecommendationRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.RecommendationsResponse.FromString,
                _registered_method=True)
        self.GenerateActivityRecommendations = channel.unary_unary(
                '/ai_platform.educational_intelligence.RecommendationEngine/GenerateActivityRecommendations',
                request_serializer=educational__intelligence__pb2.ActivityRecommendationRequest.SerializeToString,
                response_deserializer=educational__intelligence__pb2.RecommendationsResponse.FromString,
                _registered_method=True)


class RecommendationEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateContentRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateActivityRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateContentRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateContentRecommendations,
                    request_deserializer=educational__intelligence__pb2.ContentRecommendationRequest.FromString,
                    response_serializer=educational__intelligence__pb2.RecommendationsResponse.SerializeToString,
            ),
            'GenerateActivityRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateActivityRecommendations,
                    request_deserializer=educational__intelligence__pb2.ActivityRecommendationRequest.FromString,
                    response_serializer=educational__intelligence__pb2.RecommendationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_intelligence.RecommendationEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_intelligence.RecommendationEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateContentRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.RecommendationEngine/GenerateContentRecommendations',
            educational__intelligence__pb2.ContentRecommendationRequest.SerializeToString,
            educational__intelligence__pb2.RecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateActivityRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_intelligence.RecommendationEngine/GenerateActivityRecommendations',
            educational__intelligence__pb2.ActivityRecommendationRequest.SerializeToString,
            educational__intelligence__pb2.RecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
