-- 1. Student Profile Extension (Learning styles, interests, baseline)
CREATE TABLE IF NOT EXISTS cur_student_profile_ext (
    student_id uuid PRIMARY KEY REFERENCES master_student(id) ON DELETE CASCADE,
    learning_style varchar(50), -- Visual, Auditory, Kinesthetic
    dominant_interests text[],  -- Array of interests: {'Science', 'Sports', 'Art'}
    special_needs_notes text,   -- Notes on special learning requirements
    baseline_literacy varchar(50) DEFAULT 'NEEDS_IMPROVEMENT', -- Early literacy baseline
    baseline_numeracy varchar(50) DEFAULT 'NEEDS_IMPROVEMENT', -- Early numeracy baseline
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- 2. Master Observation Tags (Standardized categories for character & social emotional)
CREATE TABLE IF NOT EXISTS sys_observation_tags (
    id varchar(20) PRIMARY KEY, -- 'SEL_EMPATHY', 'MOT_GROSS', 'COG_CRITICAL'
    category varchar(50) NOT NULL, -- 'Social Emotional', 'P5 Character', 'Motor Skills', 'Habits'
    tag_name varchar(100) NOT NULL,
    sentiment varchar(10) NOT NULL -- 'POSITIVE', 'NEUTRAL', 'NEEDS_HELP'
);

-- 3. Jurnal Anecdotal Observation (Daily narrative logs)
CREATE TABLE IF NOT EXISTS trx_anecdotal_observation (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    student_id uuid NOT NULL REFERENCES master_student(id) ON DELETE CASCADE,
    teacher_id uuid NOT NULL REFERENCES master_teacher(id) ON DELETE CASCADE,
    observation_date date NOT NULL DEFAULT CURRENT_DATE,
    context_activity varchar(100), -- e.g., 'Science Group Work', 'Recess'
    notes text NOT NULL, -- Teacher narrative
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- 4. Mapping Observation to Tags (Many-to-Many relationship for analytics)
CREATE TABLE IF NOT EXISTS trx_observation_tag_mapping (
    observation_id uuid REFERENCES trx_anecdotal_observation(id) ON DELETE CASCADE,
    tag_id varchar(20) REFERENCES sys_observation_tags(id) ON DELETE CASCADE,
    PRIMARY KEY (observation_id, tag_id)
);


-- =========================================================================
-- DOMAIN: ASSESSMENT ENGINE (Flexible Assessment)
-- =========================================================================

-- 5. Assessment Instrument (Supports Formative, Summative, Numeric, and Rubrics)
CREATE TABLE IF NOT EXISTS trx_assessment_instrument (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    teaching_module_id uuid REFERENCES trx_teaching_module(id) ON DELETE SET NULL,
    learning_objective_id uuid NOT NULL REFERENCES cur_learning_objective(id) ON DELETE CASCADE, -- Linked to Learning Objective (TP)
    title varchar(150) NOT NULL,
    assessment_type varchar(20) NOT NULL, -- 'FORMATIF', 'SUMATIF'
    scoring_method varchar(20) NOT NULL,  -- 'NUMERIC', 'RUBRIC', 'OBSERVATION'
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP
);

-- 6. Student Assessment Result (Accommodates numeric scores or rubric achievements)
CREATE TABLE IF NOT EXISTS trx_student_assessment_result (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    instrument_id uuid NOT NULL REFERENCES trx_assessment_instrument(id) ON DELETE CASCADE,
    student_id uuid NOT NULL REFERENCES master_student(id) ON DELETE CASCADE,
    numeric_score numeric(5,2), -- Filled if scoring_method = NUMERIC (0-100)
    rubric_achievement varchar(50), -- Filled if RUBRIC (Mulai Berkembang, Cakap, etc)
    narrative_feedback text, -- Formative feedback from teacher
    assessed_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(instrument_id, student_id)
);


-- =========================================================================
-- DOMAIN: ACTIONABLE ANALYTICS (Early Warning System)
-- =========================================================================

-- 7. Early Warning Student Alert (Generated by background cron analysis)
CREATE TABLE IF NOT EXISTS anl_early_warning_alert (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    student_id uuid NOT NULL REFERENCES master_student(id) ON DELETE CASCADE,
    classroom_id uuid NOT NULL REFERENCES master_classroom(id) ON DELETE CASCADE,
    alert_type varchar(50) NOT NULL, -- 'LITERACY_DELAY', 'ATTENDANCE_DROP', 'BEHAVIORAL_CONCERN'
    severity_level varchar(20) NOT NULL, -- 'LOW', 'MEDIUM', 'HIGH'
    trigger_reason text NOT NULL, -- Explanation (e.g., '3x NEEDS_HELP tag in literacy')
    status varchar(20) DEFAULT 'OPEN', -- 'OPEN', 'INTERVENED', 'RESOLVED'
    intervention_notes text, -- WK/BK action logs
    detected_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    resolved_at timestamptz
);
CREATE INDEX IF NOT EXISTS idx_early_warning_status ON anl_early_warning_alert(status, severity_level);

-- SEED DATA MASTER TAGS
INSERT INTO sys_observation_tags (id, category, tag_name, sentiment) VALUES
  ('SEL_EMPATHY', 'Social Emotional', 'Empathy & Caring', 'POSITIVE'),
  ('SEL_ANGER', 'Social Emotional', 'Difficulty Managing Anger', 'NEEDS_HELP'),
  ('COG_CRITICAL', 'P5 Character', 'Critical Thinking', 'POSITIVE'),
  ('SEL_COLLABORATION', 'P5 Character', 'Collaboration & Gotong Royong', 'POSITIVE'),
  ('MOT_GROSS', 'Motor Skills', 'Independent Gross Motor Skills', 'POSITIVE'),
  ('MOT_FINE_DELAY', 'Motor Skills', 'Fine Motor Delay', 'NEEDS_HELP'),
  ('HAB_READING_DELAY', 'Habits', 'Difficulty Spelling/Reading', 'NEEDS_HELP')
ON CONFLICT (id) DO NOTHING;
