# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import generation_service_pb2 as generation__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in generation_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerationServiceStub(object):
    """Generation Service - Fase 3.3
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateText = channel.unary_unary(
                '/ai_platform.generation_service.GenerationService/GenerateText',
                request_serializer=generation__service__pb2.GenerateTextRequest.SerializeToString,
                response_deserializer=generation__service__pb2.GenerateTextResponse.FromString,
                _registered_method=True)
        self.GenerateWithContext = channel.unary_unary(
                '/ai_platform.generation_service.GenerationService/GenerateWithContext',
                request_serializer=generation__service__pb2.GenerateWithContextRequest.SerializeToString,
                response_deserializer=generation__service__pb2.GenerateWithContextResponse.FromString,
                _registered_method=True)
        self.StreamText = channel.unary_stream(
                '/ai_platform.generation_service.GenerationService/StreamText',
                request_serializer=generation__service__pb2.StreamTextRequest.SerializeToString,
                response_deserializer=generation__service__pb2.StreamTextResponse.FromString,
                _registered_method=True)
        self.GenerateQuiz = channel.unary_unary(
                '/ai_platform.generation_service.GenerationService/GenerateQuiz',
                request_serializer=generation__service__pb2.GenerateQuizRequest.SerializeToString,
                response_deserializer=generation__service__pb2.GenerateQuizResponse.FromString,
                _registered_method=True)
        self.GenerateLessonPlan = channel.unary_unary(
                '/ai_platform.generation_service.GenerationService/GenerateLessonPlan',
                request_serializer=generation__service__pb2.GenerateLessonPlanRequest.SerializeToString,
                response_deserializer=generation__service__pb2.GenerateLessonPlanResponse.FromString,
                _registered_method=True)
        self.GenerateExplanation = channel.unary_unary(
                '/ai_platform.generation_service.GenerationService/GenerateExplanation',
                request_serializer=generation__service__pb2.GenerateExplanationRequest.SerializeToString,
                response_deserializer=generation__service__pb2.GenerateExplanationResponse.FromString,
                _registered_method=True)


class GenerationServiceServicer(object):
    """Generation Service - Fase 3.3
    """

    def GenerateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateWithContext(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateQuiz(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateLessonPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateExplanation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateText': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateText,
                    request_deserializer=generation__service__pb2.GenerateTextRequest.FromString,
                    response_serializer=generation__service__pb2.GenerateTextResponse.SerializeToString,
            ),
            'GenerateWithContext': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateWithContext,
                    request_deserializer=generation__service__pb2.GenerateWithContextRequest.FromString,
                    response_serializer=generation__service__pb2.GenerateWithContextResponse.SerializeToString,
            ),
            'StreamText': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamText,
                    request_deserializer=generation__service__pb2.StreamTextRequest.FromString,
                    response_serializer=generation__service__pb2.StreamTextResponse.SerializeToString,
            ),
            'GenerateQuiz': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateQuiz,
                    request_deserializer=generation__service__pb2.GenerateQuizRequest.FromString,
                    response_serializer=generation__service__pb2.GenerateQuizResponse.SerializeToString,
            ),
            'GenerateLessonPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLessonPlan,
                    request_deserializer=generation__service__pb2.GenerateLessonPlanRequest.FromString,
                    response_serializer=generation__service__pb2.GenerateLessonPlanResponse.SerializeToString,
            ),
            'GenerateExplanation': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateExplanation,
                    request_deserializer=generation__service__pb2.GenerateExplanationRequest.FromString,
                    response_serializer=generation__service__pb2.GenerateExplanationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.generation_service.GenerationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.generation_service.GenerationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerationService(object):
    """Generation Service - Fase 3.3
    """

    @staticmethod
    def GenerateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.generation_service.GenerationService/GenerateText',
            generation__service__pb2.GenerateTextRequest.SerializeToString,
            generation__service__pb2.GenerateTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateWithContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.generation_service.GenerationService/GenerateWithContext',
            generation__service__pb2.GenerateWithContextRequest.SerializeToString,
            generation__service__pb2.GenerateWithContextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_platform.generation_service.GenerationService/StreamText',
            generation__service__pb2.StreamTextRequest.SerializeToString,
            generation__service__pb2.StreamTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateQuiz(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.generation_service.GenerationService/GenerateQuiz',
            generation__service__pb2.GenerateQuizRequest.SerializeToString,
            generation__service__pb2.GenerateQuizResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateLessonPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.generation_service.GenerationService/GenerateLessonPlan',
            generation__service__pb2.GenerateLessonPlanRequest.SerializeToString,
            generation__service__pb2.GenerateLessonPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateExplanation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.generation_service.GenerationService/GenerateExplanation',
            generation__service__pb2.GenerateExplanationRequest.SerializeToString,
            generation__service__pb2.GenerateExplanationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
