# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import advanced_enhancement_pb2 as advanced__enhancement__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in advanced_enhancement_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalEnhancementServiceStub(object):
    """Advanced Enhancement Services - Fase 6
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnhanceQuery = channel.unary_unary(
                '/ai_platform.advanced_enhancement.RetrievalEnhancementService/EnhanceQuery',
                request_serializer=advanced__enhancement__pb2.RetrievalEnhancementRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.EnhancedRetrievalResponse.FromString,
                _registered_method=True)
        self.ExpandQuery = channel.unary_unary(
                '/ai_platform.advanced_enhancement.RetrievalEnhancementService/ExpandQuery',
                request_serializer=advanced__enhancement__pb2.QueryExpansionRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.QueryExpansionResponse.FromString,
                _registered_method=True)
        self.RerankResults = channel.unary_unary(
                '/ai_platform.advanced_enhancement.RetrievalEnhancementService/RerankResults',
                request_serializer=advanced__enhancement__pb2.RerankingRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.RerankingResponse.FromString,
                _registered_method=True)


class RetrievalEnhancementServiceServicer(object):
    """Advanced Enhancement Services - Fase 6
    """

    def EnhanceQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpandQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RerankResults(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalEnhancementServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnhanceQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.EnhanceQuery,
                    request_deserializer=advanced__enhancement__pb2.RetrievalEnhancementRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.EnhancedRetrievalResponse.SerializeToString,
            ),
            'ExpandQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandQuery,
                    request_deserializer=advanced__enhancement__pb2.QueryExpansionRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.QueryExpansionResponse.SerializeToString,
            ),
            'RerankResults': grpc.unary_unary_rpc_method_handler(
                    servicer.RerankResults,
                    request_deserializer=advanced__enhancement__pb2.RerankingRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.RerankingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.advanced_enhancement.RetrievalEnhancementService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.advanced_enhancement.RetrievalEnhancementService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalEnhancementService(object):
    """Advanced Enhancement Services - Fase 6
    """

    @staticmethod
    def EnhanceQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.RetrievalEnhancementService/EnhanceQuery',
            advanced__enhancement__pb2.RetrievalEnhancementRequest.SerializeToString,
            advanced__enhancement__pb2.EnhancedRetrievalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpandQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.RetrievalEnhancementService/ExpandQuery',
            advanced__enhancement__pb2.QueryExpansionRequest.SerializeToString,
            advanced__enhancement__pb2.QueryExpansionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RerankResults(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.RetrievalEnhancementService/RerankResults',
            advanced__enhancement__pb2.RerankingRequest.SerializeToString,
            advanced__enhancement__pb2.RerankingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SemanticEnrichmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnrichContent = channel.unary_unary(
                '/ai_platform.advanced_enhancement.SemanticEnrichmentService/EnrichContent',
                request_serializer=advanced__enhancement__pb2.SemanticEnrichmentRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.EnrichmentResponse.FromString,
                _registered_method=True)
        self.GenerateEmbeddings = channel.unary_unary(
                '/ai_platform.advanced_enhancement.SemanticEnrichmentService/GenerateEmbeddings',
                request_serializer=advanced__enhancement__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.ExtractKnowledge = channel.unary_unary(
                '/ai_platform.advanced_enhancement.SemanticEnrichmentService/ExtractKnowledge',
                request_serializer=advanced__enhancement__pb2.KnowledgeExtractionRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.KnowledgeExtractionResponse.FromString,
                _registered_method=True)


class SemanticEnrichmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnrichContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractKnowledge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SemanticEnrichmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnrichContent': grpc.unary_unary_rpc_method_handler(
                    servicer.EnrichContent,
                    request_deserializer=advanced__enhancement__pb2.SemanticEnrichmentRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.EnrichmentResponse.SerializeToString,
            ),
            'GenerateEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=advanced__enhancement__pb2.EmbeddingRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.EmbeddingResponse.SerializeToString,
            ),
            'ExtractKnowledge': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractKnowledge,
                    request_deserializer=advanced__enhancement__pb2.KnowledgeExtractionRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.KnowledgeExtractionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.advanced_enhancement.SemanticEnrichmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.advanced_enhancement.SemanticEnrichmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SemanticEnrichmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnrichContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.SemanticEnrichmentService/EnrichContent',
            advanced__enhancement__pb2.SemanticEnrichmentRequest.SerializeToString,
            advanced__enhancement__pb2.EnrichmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.SemanticEnrichmentService/GenerateEmbeddings',
            advanced__enhancement__pb2.EmbeddingRequest.SerializeToString,
            advanced__enhancement__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractKnowledge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.SemanticEnrichmentService/ExtractKnowledge',
            advanced__enhancement__pb2.KnowledgeExtractionRequest.SerializeToString,
            advanced__enhancement__pb2.KnowledgeExtractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EducationalOntologyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryOntology = channel.unary_unary(
                '/ai_platform.advanced_enhancement.EducationalOntologyService/QueryOntology',
                request_serializer=advanced__enhancement__pb2.OntologyQueryRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.OntologyQueryResponse.FromString,
                _registered_method=True)
        self.ValidateAlignment = channel.unary_unary(
                '/ai_platform.advanced_enhancement.EducationalOntologyService/ValidateAlignment',
                request_serializer=advanced__enhancement__pb2.OntologyAlignmentRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.AlignmentValidationResponse.FromString,
                _registered_method=True)
        self.GetRelatedConcepts = channel.unary_unary(
                '/ai_platform.advanced_enhancement.EducationalOntologyService/GetRelatedConcepts',
                request_serializer=advanced__enhancement__pb2.RelatedConceptsRequest.SerializeToString,
                response_deserializer=advanced__enhancement__pb2.RelatedConceptsResponse.FromString,
                _registered_method=True)


class EducationalOntologyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryOntology(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateAlignment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelatedConcepts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EducationalOntologyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryOntology': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryOntology,
                    request_deserializer=advanced__enhancement__pb2.OntologyQueryRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.OntologyQueryResponse.SerializeToString,
            ),
            'ValidateAlignment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAlignment,
                    request_deserializer=advanced__enhancement__pb2.OntologyAlignmentRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.AlignmentValidationResponse.SerializeToString,
            ),
            'GetRelatedConcepts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedConcepts,
                    request_deserializer=advanced__enhancement__pb2.RelatedConceptsRequest.FromString,
                    response_serializer=advanced__enhancement__pb2.RelatedConceptsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.advanced_enhancement.EducationalOntologyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.advanced_enhancement.EducationalOntologyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EducationalOntologyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryOntology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.EducationalOntologyService/QueryOntology',
            advanced__enhancement__pb2.OntologyQueryRequest.SerializeToString,
            advanced__enhancement__pb2.OntologyQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateAlignment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.EducationalOntologyService/ValidateAlignment',
            advanced__enhancement__pb2.OntologyAlignmentRequest.SerializeToString,
            advanced__enhancement__pb2.AlignmentValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelatedConcepts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.advanced_enhancement.EducationalOntologyService/GetRelatedConcepts',
            advanced__enhancement__pb2.RelatedConceptsRequest.SerializeToString,
            advanced__enhancement__pb2.RelatedConceptsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
