# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_agents_pb2 as ai__agents__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_agents_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIAgentsServiceStub(object):
    """AI Agents Service - Fase 7
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LessonPlanningAssistant = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/LessonPlanningAssistant',
                request_serializer=ai__agents__pb2.LessonPlanningRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.LessonPlanningResponse.FromString,
                _registered_method=True)
        self.AssessmentCreationAssistant = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/AssessmentCreationAssistant',
                request_serializer=ai__agents__pb2.AssessmentCreationRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.AssessmentCreationResponse.FromString,
                _registered_method=True)
        self.StudentProgressAnalysis = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/StudentProgressAnalysis',
                request_serializer=ai__agents__pb2.StudentProgressAnalysisRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.StudentProgressAnalysisResponse.FromString,
                _registered_method=True)
        self.TeachingStrategyRecommendation = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/TeachingStrategyRecommendation',
                request_serializer=ai__agents__pb2.TeachingStrategyRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.TeachingStrategyResponse.FromString,
                _registered_method=True)
        self.PersonalizedGuidance = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/PersonalizedGuidance',
                request_serializer=ai__agents__pb2.PersonalizedGuidanceRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.PersonalizedGuidanceResponse.FromString,
                _registered_method=True)
        self.QuestionAnswering = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/QuestionAnswering',
                request_serializer=ai__agents__pb2.QuestionAnsweringRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.QuestionAnsweringResponse.FromString,
                _registered_method=True)
        self.LearningPathRecommendation = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/LearningPathRecommendation',
                request_serializer=ai__agents__pb2.LearningPathRecommendationRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.LearningPathRecommendationResponse.FromString,
                _registered_method=True)
        self.AdaptiveInteraction = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/AdaptiveInteraction',
                request_serializer=ai__agents__pb2.AdaptiveInteractionRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.AdaptiveInteractionResponse.FromString,
                _registered_method=True)
        self.CPGuidance = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/CPGuidance',
                request_serializer=ai__agents__pb2.CPGuidanceRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.CPGuidanceResponse.FromString,
                _registered_method=True)
        self.ATPGuidance = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/ATPGuidance',
                request_serializer=ai__agents__pb2.ATPGuidanceRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.ATPGuidanceResponse.FromString,
                _registered_method=True)
        self.CurriculumAlignmentChecking = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/CurriculumAlignmentChecking',
                request_serializer=ai__agents__pb2.CurriculumAlignmentRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.CurriculumAlignmentResponse.FromString,
                _registered_method=True)
        self.CurriculumRecommendation = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/CurriculumRecommendation',
                request_serializer=ai__agents__pb2.CurriculumRecommendationRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.CurriculumRecommendationResponse.FromString,
                _registered_method=True)
        self.ExpertKnowledgeIntegration = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/ExpertKnowledgeIntegration',
                request_serializer=ai__agents__pb2.ExpertKnowledgeRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.ExpertKnowledgeResponse.FromString,
                _registered_method=True)
        self.AssessmentGenerationAssistant = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/AssessmentGenerationAssistant',
                request_serializer=ai__agents__pb2.AssessmentGenerationRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.AssessmentGenerationResponse.FromString,
                _registered_method=True)
        self.RubricCreationAssistant = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/RubricCreationAssistant',
                request_serializer=ai__agents__pb2.RubricCreationRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.RubricCreationResponse.FromString,
                _registered_method=True)
        self.AssessmentAnalytics = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/AssessmentAnalytics',
                request_serializer=ai__agents__pb2.AssessmentAnalyticsRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.AssessmentAnalyticsResponse.FromString,
                _registered_method=True)
        self.QualityValidation = channel.unary_unary(
                '/ai_platform.ai_agents.AIAgentsService/QualityValidation',
                request_serializer=ai__agents__pb2.QualityValidationRequest.SerializeToString,
                response_deserializer=ai__agents__pb2.QualityValidationResponse.FromString,
                _registered_method=True)


class AIAgentsServiceServicer(object):
    """AI Agents Service - Fase 7
    """

    def LessonPlanningAssistant(self, request, context):
        """Teacher Agent Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessmentCreationAssistant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StudentProgressAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TeachingStrategyRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PersonalizedGuidance(self, request, context):
        """Student Learning Agent Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuestionAnswering(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LearningPathRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AdaptiveInteraction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CPGuidance(self, request, context):
        """Curriculum Agent Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ATPGuidance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurriculumAlignmentChecking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CurriculumRecommendation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExpertKnowledgeIntegration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessmentGenerationAssistant(self, request, context):
        """Assessment Agent Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RubricCreationAssistant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssessmentAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QualityValidation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIAgentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LessonPlanningAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.LessonPlanningAssistant,
                    request_deserializer=ai__agents__pb2.LessonPlanningRequest.FromString,
                    response_serializer=ai__agents__pb2.LessonPlanningResponse.SerializeToString,
            ),
            'AssessmentCreationAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessmentCreationAssistant,
                    request_deserializer=ai__agents__pb2.AssessmentCreationRequest.FromString,
                    response_serializer=ai__agents__pb2.AssessmentCreationResponse.SerializeToString,
            ),
            'StudentProgressAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.StudentProgressAnalysis,
                    request_deserializer=ai__agents__pb2.StudentProgressAnalysisRequest.FromString,
                    response_serializer=ai__agents__pb2.StudentProgressAnalysisResponse.SerializeToString,
            ),
            'TeachingStrategyRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.TeachingStrategyRecommendation,
                    request_deserializer=ai__agents__pb2.TeachingStrategyRequest.FromString,
                    response_serializer=ai__agents__pb2.TeachingStrategyResponse.SerializeToString,
            ),
            'PersonalizedGuidance': grpc.unary_unary_rpc_method_handler(
                    servicer.PersonalizedGuidance,
                    request_deserializer=ai__agents__pb2.PersonalizedGuidanceRequest.FromString,
                    response_serializer=ai__agents__pb2.PersonalizedGuidanceResponse.SerializeToString,
            ),
            'QuestionAnswering': grpc.unary_unary_rpc_method_handler(
                    servicer.QuestionAnswering,
                    request_deserializer=ai__agents__pb2.QuestionAnsweringRequest.FromString,
                    response_serializer=ai__agents__pb2.QuestionAnsweringResponse.SerializeToString,
            ),
            'LearningPathRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.LearningPathRecommendation,
                    request_deserializer=ai__agents__pb2.LearningPathRecommendationRequest.FromString,
                    response_serializer=ai__agents__pb2.LearningPathRecommendationResponse.SerializeToString,
            ),
            'AdaptiveInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.AdaptiveInteraction,
                    request_deserializer=ai__agents__pb2.AdaptiveInteractionRequest.FromString,
                    response_serializer=ai__agents__pb2.AdaptiveInteractionResponse.SerializeToString,
            ),
            'CPGuidance': grpc.unary_unary_rpc_method_handler(
                    servicer.CPGuidance,
                    request_deserializer=ai__agents__pb2.CPGuidanceRequest.FromString,
                    response_serializer=ai__agents__pb2.CPGuidanceResponse.SerializeToString,
            ),
            'ATPGuidance': grpc.unary_unary_rpc_method_handler(
                    servicer.ATPGuidance,
                    request_deserializer=ai__agents__pb2.ATPGuidanceRequest.FromString,
                    response_serializer=ai__agents__pb2.ATPGuidanceResponse.SerializeToString,
            ),
            'CurriculumAlignmentChecking': grpc.unary_unary_rpc_method_handler(
                    servicer.CurriculumAlignmentChecking,
                    request_deserializer=ai__agents__pb2.CurriculumAlignmentRequest.FromString,
                    response_serializer=ai__agents__pb2.CurriculumAlignmentResponse.SerializeToString,
            ),
            'CurriculumRecommendation': grpc.unary_unary_rpc_method_handler(
                    servicer.CurriculumRecommendation,
                    request_deserializer=ai__agents__pb2.CurriculumRecommendationRequest.FromString,
                    response_serializer=ai__agents__pb2.CurriculumRecommendationResponse.SerializeToString,
            ),
            'ExpertKnowledgeIntegration': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpertKnowledgeIntegration,
                    request_deserializer=ai__agents__pb2.ExpertKnowledgeRequest.FromString,
                    response_serializer=ai__agents__pb2.ExpertKnowledgeResponse.SerializeToString,
            ),
            'AssessmentGenerationAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessmentGenerationAssistant,
                    request_deserializer=ai__agents__pb2.AssessmentGenerationRequest.FromString,
                    response_serializer=ai__agents__pb2.AssessmentGenerationResponse.SerializeToString,
            ),
            'RubricCreationAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.RubricCreationAssistant,
                    request_deserializer=ai__agents__pb2.RubricCreationRequest.FromString,
                    response_serializer=ai__agents__pb2.RubricCreationResponse.SerializeToString,
            ),
            'AssessmentAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.AssessmentAnalytics,
                    request_deserializer=ai__agents__pb2.AssessmentAnalyticsRequest.FromString,
                    response_serializer=ai__agents__pb2.AssessmentAnalyticsResponse.SerializeToString,
            ),
            'QualityValidation': grpc.unary_unary_rpc_method_handler(
                    servicer.QualityValidation,
                    request_deserializer=ai__agents__pb2.QualityValidationRequest.FromString,
                    response_serializer=ai__agents__pb2.QualityValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.ai_agents.AIAgentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.ai_agents.AIAgentsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIAgentsService(object):
    """AI Agents Service - Fase 7
    """

    @staticmethod
    def LessonPlanningAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/LessonPlanningAssistant',
            ai__agents__pb2.LessonPlanningRequest.SerializeToString,
            ai__agents__pb2.LessonPlanningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssessmentCreationAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/AssessmentCreationAssistant',
            ai__agents__pb2.AssessmentCreationRequest.SerializeToString,
            ai__agents__pb2.AssessmentCreationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StudentProgressAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/StudentProgressAnalysis',
            ai__agents__pb2.StudentProgressAnalysisRequest.SerializeToString,
            ai__agents__pb2.StudentProgressAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TeachingStrategyRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/TeachingStrategyRecommendation',
            ai__agents__pb2.TeachingStrategyRequest.SerializeToString,
            ai__agents__pb2.TeachingStrategyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PersonalizedGuidance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/PersonalizedGuidance',
            ai__agents__pb2.PersonalizedGuidanceRequest.SerializeToString,
            ai__agents__pb2.PersonalizedGuidanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuestionAnswering(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/QuestionAnswering',
            ai__agents__pb2.QuestionAnsweringRequest.SerializeToString,
            ai__agents__pb2.QuestionAnsweringResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LearningPathRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/LearningPathRecommendation',
            ai__agents__pb2.LearningPathRecommendationRequest.SerializeToString,
            ai__agents__pb2.LearningPathRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AdaptiveInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/AdaptiveInteraction',
            ai__agents__pb2.AdaptiveInteractionRequest.SerializeToString,
            ai__agents__pb2.AdaptiveInteractionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CPGuidance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/CPGuidance',
            ai__agents__pb2.CPGuidanceRequest.SerializeToString,
            ai__agents__pb2.CPGuidanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ATPGuidance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/ATPGuidance',
            ai__agents__pb2.ATPGuidanceRequest.SerializeToString,
            ai__agents__pb2.ATPGuidanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CurriculumAlignmentChecking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/CurriculumAlignmentChecking',
            ai__agents__pb2.CurriculumAlignmentRequest.SerializeToString,
            ai__agents__pb2.CurriculumAlignmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CurriculumRecommendation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/CurriculumRecommendation',
            ai__agents__pb2.CurriculumRecommendationRequest.SerializeToString,
            ai__agents__pb2.CurriculumRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExpertKnowledgeIntegration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/ExpertKnowledgeIntegration',
            ai__agents__pb2.ExpertKnowledgeRequest.SerializeToString,
            ai__agents__pb2.ExpertKnowledgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssessmentGenerationAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/AssessmentGenerationAssistant',
            ai__agents__pb2.AssessmentGenerationRequest.SerializeToString,
            ai__agents__pb2.AssessmentGenerationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RubricCreationAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/RubricCreationAssistant',
            ai__agents__pb2.RubricCreationRequest.SerializeToString,
            ai__agents__pb2.RubricCreationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssessmentAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/AssessmentAnalytics',
            ai__agents__pb2.AssessmentAnalyticsRequest.SerializeToString,
            ai__agents__pb2.AssessmentAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QualityValidation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.ai_agents.AIAgentsService/QualityValidation',
            ai__agents__pb2.QualityValidationRequest.SerializeToString,
            ai__agents__pb2.QualityValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
