# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import educational_observability_pb2 as educational__observability__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in educational_observability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EducationalObservabilityServiceStub(object):
    """Educational Observability Service - Fase 8.2
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateLearningAnalytics = channel.unary_unary(
                '/ai_platform.educational_observability.EducationalObservabilityService/GenerateLearningAnalytics',
                request_serializer=educational__observability__pb2.LearningAnalyticsRequest.SerializeToString,
                response_deserializer=educational__observability__pb2.AnalyticsResult.FromString,
                _registered_method=True)
        self.GenerateCompetencyAnalytics = channel.unary_unary(
                '/ai_platform.educational_observability.EducationalObservabilityService/GenerateCompetencyAnalytics',
                request_serializer=educational__observability__pb2.CompetencyAnalyticsRequest.SerializeToString,
                response_deserializer=educational__observability__pb2.AnalyticsResult.FromString,
                _registered_method=True)
        self.MonitorAssessmentQuality = channel.unary_unary(
                '/ai_platform.educational_observability.EducationalObservabilityService/MonitorAssessmentQuality',
                request_serializer=educational__observability__pb2.AssessmentQualityMonitoringRequest.SerializeToString,
                response_deserializer=educational__observability__pb2.MonitoringResult.FromString,
                _registered_method=True)
        self.MonitorRetrievalQuality = channel.unary_unary(
                '/ai_platform.educational_observability.EducationalObservabilityService/MonitorRetrievalQuality',
                request_serializer=educational__observability__pb2.RetrievalQualityMonitoringRequest.SerializeToString,
                response_deserializer=educational__observability__pb2.MonitoringResult.FromString,
                _registered_method=True)
        self.MonitorPedagogyEffectiveness = channel.unary_unary(
                '/ai_platform.educational_observability.EducationalObservabilityService/MonitorPedagogyEffectiveness',
                request_serializer=educational__observability__pb2.PedagogyEffectivenessMonitoringRequest.SerializeToString,
                response_deserializer=educational__observability__pb2.MonitoringResult.FromString,
                _registered_method=True)
        self.MonitorHallucinations = channel.unary_unary(
                '/ai_platform.educational_observability.EducationalObservabilityService/MonitorHallucinations',
                request_serializer=educational__observability__pb2.HallucinationMonitoringRequest.SerializeToString,
                response_deserializer=educational__observability__pb2.MonitoringResult.FromString,
                _registered_method=True)


class EducationalObservabilityServiceServicer(object):
    """Educational Observability Service - Fase 8.2
    """

    def GenerateLearningAnalytics(self, request, context):
        """Analytics Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateCompetencyAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorAssessmentQuality(self, request, context):
        """Monitoring Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorRetrievalQuality(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorPedagogyEffectiveness(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MonitorHallucinations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EducationalObservabilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateLearningAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateLearningAnalytics,
                    request_deserializer=educational__observability__pb2.LearningAnalyticsRequest.FromString,
                    response_serializer=educational__observability__pb2.AnalyticsResult.SerializeToString,
            ),
            'GenerateCompetencyAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateCompetencyAnalytics,
                    request_deserializer=educational__observability__pb2.CompetencyAnalyticsRequest.FromString,
                    response_serializer=educational__observability__pb2.AnalyticsResult.SerializeToString,
            ),
            'MonitorAssessmentQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.MonitorAssessmentQuality,
                    request_deserializer=educational__observability__pb2.AssessmentQualityMonitoringRequest.FromString,
                    response_serializer=educational__observability__pb2.MonitoringResult.SerializeToString,
            ),
            'MonitorRetrievalQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.MonitorRetrievalQuality,
                    request_deserializer=educational__observability__pb2.RetrievalQualityMonitoringRequest.FromString,
                    response_serializer=educational__observability__pb2.MonitoringResult.SerializeToString,
            ),
            'MonitorPedagogyEffectiveness': grpc.unary_unary_rpc_method_handler(
                    servicer.MonitorPedagogyEffectiveness,
                    request_deserializer=educational__observability__pb2.PedagogyEffectivenessMonitoringRequest.FromString,
                    response_serializer=educational__observability__pb2.MonitoringResult.SerializeToString,
            ),
            'MonitorHallucinations': grpc.unary_unary_rpc_method_handler(
                    servicer.MonitorHallucinations,
                    request_deserializer=educational__observability__pb2.HallucinationMonitoringRequest.FromString,
                    response_serializer=educational__observability__pb2.MonitoringResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.educational_observability.EducationalObservabilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.educational_observability.EducationalObservabilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EducationalObservabilityService(object):
    """Educational Observability Service - Fase 8.2
    """

    @staticmethod
    def GenerateLearningAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_observability.EducationalObservabilityService/GenerateLearningAnalytics',
            educational__observability__pb2.LearningAnalyticsRequest.SerializeToString,
            educational__observability__pb2.AnalyticsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateCompetencyAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_observability.EducationalObservabilityService/GenerateCompetencyAnalytics',
            educational__observability__pb2.CompetencyAnalyticsRequest.SerializeToString,
            educational__observability__pb2.AnalyticsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorAssessmentQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_observability.EducationalObservabilityService/MonitorAssessmentQuality',
            educational__observability__pb2.AssessmentQualityMonitoringRequest.SerializeToString,
            educational__observability__pb2.MonitoringResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorRetrievalQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_observability.EducationalObservabilityService/MonitorRetrievalQuality',
            educational__observability__pb2.RetrievalQualityMonitoringRequest.SerializeToString,
            educational__observability__pb2.MonitoringResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorPedagogyEffectiveness(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_observability.EducationalObservabilityService/MonitorPedagogyEffectiveness',
            educational__observability__pb2.PedagogyEffectivenessMonitoringRequest.SerializeToString,
            educational__observability__pb2.MonitoringResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MonitorHallucinations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.educational_observability.EducationalObservabilityService/MonitorHallucinations',
            educational__observability__pb2.HallucinationMonitoringRequest.SerializeToString,
            educational__observability__pb2.MonitoringResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
