import { MenuItem } from "@/types/types";

export const leftMenuItems: MenuItem[] = [
  {
    id: "home",
    icon: "NiHome",
    label: "menu-home",
    href: "/home",
    color: "text-primary",
    children: [
      {
        id: "dashboard",
        label: "menu-summary",
        icon: "NiDashboard",
        href: "/home/board/summary",
      },
    ],
  },
  {
    id: "data-induk",
    icon: "NiBuilding",
    label: "menu-institution",
    href: "/profile",
    color: "text-primary",
    children: [
      { id: "school-profile", label: "menu-school", icon: "NiBuilding", href: "/profile/school" },
      { id: "staff-data", label: "menu-character-building", icon: "NiBadge", href: "/academic/subjects/staff" },
      { id: "student-data", label: "menu-data-students", icon: "NiUsers", href: "/students" },
      { id: "evidence-data", label: "menu-evidence", icon: "NiFolder", href: "/students/evidence" },
      { id: "growth-data", label: "menu-growth", icon: "NiChartBar", href: "/students/growth" },
      {
        id: "character-growth-data",
        label: "menu-character-growth",
        icon: "NiStar",
        href: "/students/character-growth",
      },
      { id: "spmb-data", label: "menu-spmb-online", icon: "NiBadge", href: "/spmb/admin" },
      { id: "class-data", label: "menu-data-classes", icon: "NiLayout", href: "/academic/subjects/classroom" },
      { id: "teacher-workload", label: "menu-teacher-workload", icon: "NiUser", href: "/teachers/workload" },
      { id: "teacher-reflection", label: "menu-teacher-reflection", icon: "NiBook", href: "/teachers/reflection" },
    ],
  },
  {
    id: "kurikulum",
    icon: "NiBook",
    label: "menu-curriculum",
    href: "/academic/curriculum",
    color: "text-primary",
    children: [
      {
        id: "standar-belajar",
        label: "menu-data-master",
        icon: "NiArchive",
        href: "/academic/curriculum",
        children: [
          { id: "phases", label: "menu-phases", href: "/academic/phases" },
          { id: "subjects", label: "menu-subjects", href: "/academic/subjects" },
          { id: "standards", label: "menu-standards", href: "/academic/curriculum" },
          { id: "objectives", label: "menu-objectives", href: "/academic/curriculum/objectives" },
          { id: "flow", label: "menu-flow", href: "/academic/curriculum/flow" },
          { id: "dimensions", label: "menu-dimensions", href: "/academic/dimensions" },
        ],
      },
      { id: "characteristics", label: "menu-data-local", icon: "NiMap", href: "/local-context" },
      { id: "ksp-doc", label: "menu-ksp-builder", icon: "NiPen", href: "/academic/ksp" },
      { id: "kokurikuler", label: "menu-kokurikuler", icon: "NiCalendar", href: "/academic/curriculum/kokurikuler" },
      {
        id: "ekstrakurikuler",
        label: "menu-ekstrakurikuler",
        icon: "NiBriefcase",
        href: "/academic/curriculum/ekstrakurikuler",
      },
    ],
  },
  {
    id: "pembelajaran",
    icon: "NiGraduation",
    label: "menu-learning",
    href: "/learning",
    color: "text-primary",
    children: [
      { id: "class-schedule", label: "menu-class-schedule", icon: "NiCalendar", href: "/academic/subjects/schedule" },
      { id: "presence", label: "menu-daily-presence", icon: "NiCheckFull", href: "/students/presence/daily" },
      {
        id: "teaching-modules",
        label: "menu-modules",
        icon: "NiArchive",
        href: "/learning/modules",
        children: [
          { id: "drafts", label: "menu-drafts", href: "/learning/modules/drafts" },
          { id: "library", label: "menu-library", href: "/learning/modules/library" },
        ],
      },
      { id: "p5-projects", label: "menu-projects", icon: "NiBriefcase", href: "/learning/projects/plans" },
      { id: "lesson-planning", label: "menu-lesson-planning", icon: "NiBook", href: "/learning/lesson-plans" },
      { id: "intervention", label: "menu-intervention", icon: "NiHeart", href: "/learning/intervention" },
    ],
  },
  {
    id: "sd-spesifik",
    icon: "NiUsers",
    label: "menu-sd-specifics",
    href: "/academic/foundational-skills",
    color: "text-primary",
    children: [
      {
        id: "foundational-skills",
        label: "menu-foundational-skills",
        icon: "NiBook",
        href: "/academic/foundational-skills",
        children: [
          {
            id: "foundational-skills-assessment",
            label: "menu-foundational-assessment",
            href: "/academic/foundational-skills/assessment",
          },
          {
            id: "foundational-skills-progress",
            label: "menu-foundational-progress",
            href: "/academic/foundational-skills/progress",
          },
        ],
      },
      {
        id: "reading-literacy",
        label: "menu-reading-literacy",
        icon: "NiArchive",
        href: "/academic/reading-literacy",
        children: [
          {
            id: "reading-literacy-assessment",
            label: "menu-reading-assessment",
            href: "/academic/reading-literacy/assessment",
          },
          {
            id: "reading-literacy-progression",
            label: "menu-reading-progression",
            href: "/academic/reading-literacy/progression",
          },
        ],
      },
      {
        id: "numeracy",
        label: "menu-numeracy",
        icon: "NiChartBar",
        href: "/academic/numeracy",
      },
    ],
  },
  {
    id: "asesmen",
    icon: "NiPen",
    label: "menu-assessment",
    href: "/academic/evaluation",
    color: "text-primary",
    children: [
      { id: "question-bank", label: "menu-question-bank", icon: "NiArchive", href: "/academic/question-bank" },
      { id: "formative", label: "menu-formative-value", icon: "NiChartBar", href: "/academic/evaluation/formative" },
      { id: "summative", label: "menu-summative-value", icon: "NiStar", href: "/academic/evaluation/summative" },
      {
        id: "sd-criteria",
        label: "menu-sd-assessment-criteria",
        icon: "NiCheckFull",
        href: "/academic/evaluation/criteria",
      },
      {
        id: "portfolio",
        label: "menu-portfolio",
        icon: "NiFolder",
        href: "/academic/evaluation/portfolio",
      },
      {
        id: "rubric",
        label: "menu-rubric",
        icon: "NiCheckFull",
        href: "/academic/evaluation/rubric",
      },
      {
        id: "supervision",
        label: "menu-supervision",
        icon: "NiSearch",
        href: "/academic/supervision",
      },
    ],
  },
  {
    id: "laporan",
    icon: "NiDocumentChart",
    label: "menu-reports",
    href: "/reports",
    color: "text-primary",
    children: [
      { id: "p5-achievement", label: "menu-project-scores", icon: "NiHeart", href: "/learning/projects/results" },
      { id: "gradebook-recap", label: "menu-gradebook", icon: "NiBook", href: "/reports/gradebook/scores" },
      { id: "print-rapport", label: "menu-print", icon: "NiPrinter", href: "/reports/gradebook/print" },
    ],
  },
  {
    id: "analytics",
    icon: "NiChartBar",
    label: "menu-analytics-section",
    href: "/analytics/learning",
    color: "text-primary",
    children: [
      { id: "learning-analytics", label: "menu-learning-analytics", icon: "NiChartBar", href: "/analytics/learning" },
    ],
  },
  {
    id: "komunikasi",
    icon: "NiAnnouncement",
    label: "menu-communication",
    href: "/communication",
    color: "text-primary",
    children: [
      { id: "announcements", label: "menu-announcements", icon: "NiAnnouncement", href: "/communication" },
      { id: "messages", label: "menu-messages", icon: "NiEmail", href: "/communication" },
    ],
  },
];

export const leftMenuBottomItems: MenuItem[] = [
  {
    id: "sistem",
    icon: "NiCpu",
    label: "menu-system",
    href: "/system",
    color: "text-primary",
    children: [
      { id: "access-rights", label: "menu-access-rights", icon: "NiLock", href: "/system/access" },
      { id: "academic-year", label: "menu-academic-year-cycle", icon: "NiCalendar", href: "/system/academic-years" },
      { id: "grade-level", label: "menu-grade-master", icon: "NiLayout", href: "/system/grades" },
      { id: "system-status", label: "menu-data-index", icon: "NiChartBar", href: "/system/engine" },
      {
        id: "database-monitoring",
        label: "menu-database-monitoring",
        icon: "NiStore",
        href: "/system/database-monitoring",
      },
      {
        id: "document-repository",
        label: "menu-document-repository",
        icon: "NiFolder",
        href: "/system/document-repository",
      },
      { id: "offline-sync", label: "menu-offline-sync", icon: "NiRefresh", href: "/system/offline" },
    ],
  },
  { id: "guide", label: "menu-guide", href: "/docs", icon: "NiBook", color: "text-primary" },
  { id: "settings", label: "menu-settings", href: "/settings", icon: "NiSettings" },
];
