// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: retrieval_service.proto

package retrievalservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Retrieval Service Messages
type SemanticSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	QueryText      string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	CollectionName string                 `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Limit          int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Filters        map[string]string      `protobuf:"bytes,5,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options        map[string]string      `protobuf:"bytes,6,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_retrieval_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{0}
}

func (x *SemanticSearchRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SemanticSearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *SemanticSearchRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *SemanticSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SemanticSearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SemanticSearchRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *SearchResult          `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_retrieval_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{1}
}

func (x *SemanticSearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SemanticSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SemanticSearchResponse) GetResult() *SearchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SemanticSearchResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*RetrievedDocument   `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	Summary       *SearchSummary         `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_retrieval_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResult) GetDocuments() []*RetrievedDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *SearchResult) GetSummary() *SearchSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type RetrievedDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocumentId    string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Score         float32                `protobuf:"fixed32,3,opt,name=score,proto3" json:"score,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievedDocument) Reset() {
	*x = RetrievedDocument{}
	mi := &file_retrieval_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievedDocument) ProtoMessage() {}

func (x *RetrievedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievedDocument.ProtoReflect.Descriptor instead.
func (*RetrievedDocument) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{3}
}

func (x *RetrievedDocument) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RetrievedDocument) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *RetrievedDocument) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RetrievedDocument) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TotalResults   int32                  `protobuf:"varint,1,opt,name=total_results,json=totalResults,proto3" json:"total_results,omitempty"`
	SearchTimeMs   float32                `protobuf:"fixed32,2,opt,name=search_time_ms,json=searchTimeMs,proto3" json:"search_time_ms,omitempty"`
	SearchStrategy string                 `protobuf:"bytes,3,opt,name=search_strategy,json=searchStrategy,proto3" json:"search_strategy,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchSummary) Reset() {
	*x = SearchSummary{}
	mi := &file_retrieval_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchSummary) ProtoMessage() {}

func (x *SearchSummary) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchSummary.ProtoReflect.Descriptor instead.
func (*SearchSummary) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{4}
}

func (x *SearchSummary) GetTotalResults() int32 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *SearchSummary) GetSearchTimeMs() float32 {
	if x != nil {
		return x.SearchTimeMs
	}
	return 0
}

func (x *SearchSummary) GetSearchStrategy() string {
	if x != nil {
		return x.SearchStrategy
	}
	return ""
}

type HybridSearchRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryId        string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	QueryText      string                 `protobuf:"bytes,2,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	CollectionName string                 `protobuf:"bytes,3,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	SemanticWeight float32                `protobuf:"fixed32,4,opt,name=semantic_weight,json=semanticWeight,proto3" json:"semantic_weight,omitempty"`
	KeywordWeight  float32                `protobuf:"fixed32,5,opt,name=keyword_weight,json=keywordWeight,proto3" json:"keyword_weight,omitempty"`
	Limit          int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Filters        map[string]string      `protobuf:"bytes,7,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options        map[string]string      `protobuf:"bytes,8,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HybridSearchRequest) Reset() {
	*x = HybridSearchRequest{}
	mi := &file_retrieval_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchRequest) ProtoMessage() {}

func (x *HybridSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{5}
}

func (x *HybridSearchRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *HybridSearchRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *HybridSearchRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *HybridSearchRequest) GetSemanticWeight() float32 {
	if x != nil {
		return x.SemanticWeight
	}
	return 0
}

func (x *HybridSearchRequest) GetKeywordWeight() float32 {
	if x != nil {
		return x.KeywordWeight
	}
	return 0
}

func (x *HybridSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *HybridSearchRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *HybridSearchRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type HybridSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *SearchResult          `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchResponse) Reset() {
	*x = HybridSearchResponse{}
	mi := &file_retrieval_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchResponse) ProtoMessage() {}

func (x *HybridSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{6}
}

func (x *HybridSearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HybridSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HybridSearchResponse) GetResult() *SearchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *HybridSearchResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FilterByMetadataRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CollectionName string                 `protobuf:"bytes,1,opt,name=collection_name,json=collectionName,proto3" json:"collection_name,omitempty"`
	Filters        map[string]string      `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Limit          int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Options        map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilterByMetadataRequest) Reset() {
	*x = FilterByMetadataRequest{}
	mi := &file_retrieval_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterByMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterByMetadataRequest) ProtoMessage() {}

func (x *FilterByMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterByMetadataRequest.ProtoReflect.Descriptor instead.
func (*FilterByMetadataRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{7}
}

func (x *FilterByMetadataRequest) GetCollectionName() string {
	if x != nil {
		return x.CollectionName
	}
	return ""
}

func (x *FilterByMetadataRequest) GetFilters() map[string]string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *FilterByMetadataRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *FilterByMetadataRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type FilterByMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *FilterResult          `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterByMetadataResponse) Reset() {
	*x = FilterByMetadataResponse{}
	mi := &file_retrieval_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterByMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterByMetadataResponse) ProtoMessage() {}

func (x *FilterByMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterByMetadataResponse.ProtoReflect.Descriptor instead.
func (*FilterByMetadataResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{8}
}

func (x *FilterByMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FilterByMetadataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FilterByMetadataResponse) GetResult() *FilterResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *FilterByMetadataResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type FilterResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Documents      []*RetrievedDocument   `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	TotalFiltered  int32                  `protobuf:"varint,2,opt,name=total_filtered,json=totalFiltered,proto3" json:"total_filtered,omitempty"`
	AppliedFilters []string               `protobuf:"bytes,3,rep,name=applied_filters,json=appliedFilters,proto3" json:"applied_filters,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilterResult) Reset() {
	*x = FilterResult{}
	mi := &file_retrieval_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterResult) ProtoMessage() {}

func (x *FilterResult) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterResult.ProtoReflect.Descriptor instead.
func (*FilterResult) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{9}
}

func (x *FilterResult) GetDocuments() []*RetrievedDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *FilterResult) GetTotalFiltered() int32 {
	if x != nil {
		return x.TotalFiltered
	}
	return 0
}

func (x *FilterResult) GetAppliedFilters() []string {
	if x != nil {
		return x.AppliedFilters
	}
	return nil
}

type BuildContextRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueryId          string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Documents        []*RetrievedDocument   `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	MaxContextLength int32                  `protobuf:"varint,3,opt,name=max_context_length,json=maxContextLength,proto3" json:"max_context_length,omitempty"`
	Options          map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BuildContextRequest) Reset() {
	*x = BuildContextRequest{}
	mi := &file_retrieval_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildContextRequest) ProtoMessage() {}

func (x *BuildContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildContextRequest.ProtoReflect.Descriptor instead.
func (*BuildContextRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{10}
}

func (x *BuildContextRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *BuildContextRequest) GetDocuments() []*RetrievedDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *BuildContextRequest) GetMaxContextLength() int32 {
	if x != nil {
		return x.MaxContextLength
	}
	return 0
}

func (x *BuildContextRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type BuildContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *ContextResult         `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildContextResponse) Reset() {
	*x = BuildContextResponse{}
	mi := &file_retrieval_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildContextResponse) ProtoMessage() {}

func (x *BuildContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildContextResponse.ProtoReflect.Descriptor instead.
func (*BuildContextResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{11}
}

func (x *BuildContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BuildContextResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildContextResponse) GetResult() *ContextResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *BuildContextResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ContextResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       string                 `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Sources       []*ContextSource       `protobuf:"bytes,2,rep,name=sources,proto3" json:"sources,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContextResult) Reset() {
	*x = ContextResult{}
	mi := &file_retrieval_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextResult) ProtoMessage() {}

func (x *ContextResult) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextResult.ProtoReflect.Descriptor instead.
func (*ContextResult) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{12}
}

func (x *ContextResult) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *ContextResult) GetSources() []*ContextSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ContextResult) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

type ContextSource struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DocumentId       string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	UsedChunkIndices []int32                `protobuf:"varint,2,rep,packed,name=used_chunk_indices,json=usedChunkIndices,proto3" json:"used_chunk_indices,omitempty"`
	Snippet          string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ContextSource) Reset() {
	*x = ContextSource{}
	mi := &file_retrieval_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContextSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextSource) ProtoMessage() {}

func (x *ContextSource) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextSource.ProtoReflect.Descriptor instead.
func (*ContextSource) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{13}
}

func (x *ContextSource) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ContextSource) GetUsedChunkIndices() []int32 {
	if x != nil {
		return x.UsedChunkIndices
	}
	return nil
}

func (x *ContextSource) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type ExpandQueryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	QueryId           string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	OriginalQuery     string                 `protobuf:"bytes,2,opt,name=original_query,json=originalQuery,proto3" json:"original_query,omitempty"`
	ExpansionStrategy string                 `protobuf:"bytes,3,opt,name=expansion_strategy,json=expansionStrategy,proto3" json:"expansion_strategy,omitempty"`
	NumExpansions     int32                  `protobuf:"varint,4,opt,name=num_expansions,json=numExpansions,proto3" json:"num_expansions,omitempty"`
	Options           map[string]string      `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ExpandQueryRequest) Reset() {
	*x = ExpandQueryRequest{}
	mi := &file_retrieval_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandQueryRequest) ProtoMessage() {}

func (x *ExpandQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandQueryRequest.ProtoReflect.Descriptor instead.
func (*ExpandQueryRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{14}
}

func (x *ExpandQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *ExpandQueryRequest) GetOriginalQuery() string {
	if x != nil {
		return x.OriginalQuery
	}
	return ""
}

func (x *ExpandQueryRequest) GetExpansionStrategy() string {
	if x != nil {
		return x.ExpansionStrategy
	}
	return ""
}

func (x *ExpandQueryRequest) GetNumExpansions() int32 {
	if x != nil {
		return x.NumExpansions
	}
	return 0
}

func (x *ExpandQueryRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type ExpandQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *QueryExpansionResult  `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandQueryResponse) Reset() {
	*x = ExpandQueryResponse{}
	mi := &file_retrieval_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandQueryResponse) ProtoMessage() {}

func (x *ExpandQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandQueryResponse.ProtoReflect.Descriptor instead.
func (*ExpandQueryResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{15}
}

func (x *ExpandQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExpandQueryResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExpandQueryResponse) GetResult() *QueryExpansionResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExpandQueryResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type QueryExpansionResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ExpandedQueries []*ExpandedQuery       `protobuf:"bytes,1,rep,name=expanded_queries,json=expandedQueries,proto3" json:"expanded_queries,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryExpansionResult) Reset() {
	*x = QueryExpansionResult{}
	mi := &file_retrieval_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryExpansionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryExpansionResult) ProtoMessage() {}

func (x *QueryExpansionResult) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryExpansionResult.ProtoReflect.Descriptor instead.
func (*QueryExpansionResult) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{16}
}

func (x *QueryExpansionResult) GetExpandedQueries() []*ExpandedQuery {
	if x != nil {
		return x.ExpandedQueries
	}
	return nil
}

type ExpandedQuery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	QueryText      string                 `protobuf:"bytes,1,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	ExpansionScore float32                `protobuf:"fixed32,2,opt,name=expansion_score,json=expansionScore,proto3" json:"expansion_score,omitempty"`
	ExpansionType  string                 `protobuf:"bytes,3,opt,name=expansion_type,json=expansionType,proto3" json:"expansion_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExpandedQuery) Reset() {
	*x = ExpandedQuery{}
	mi := &file_retrieval_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandedQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandedQuery) ProtoMessage() {}

func (x *ExpandedQuery) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandedQuery.ProtoReflect.Descriptor instead.
func (*ExpandedQuery) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{17}
}

func (x *ExpandedQuery) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *ExpandedQuery) GetExpansionScore() float32 {
	if x != nil {
		return x.ExpansionScore
	}
	return 0
}

func (x *ExpandedQuery) GetExpansionType() string {
	if x != nil {
		return x.ExpansionType
	}
	return ""
}

type GetRelevanceScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Documents     []*RetrievedDocument   `protobuf:"bytes,2,rep,name=documents,proto3" json:"documents,omitempty"`
	QueryText     string                 `protobuf:"bytes,3,opt,name=query_text,json=queryText,proto3" json:"query_text,omitempty"`
	Options       map[string]string      `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelevanceScoresRequest) Reset() {
	*x = GetRelevanceScoresRequest{}
	mi := &file_retrieval_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelevanceScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelevanceScoresRequest) ProtoMessage() {}

func (x *GetRelevanceScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelevanceScoresRequest.ProtoReflect.Descriptor instead.
func (*GetRelevanceScoresRequest) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{18}
}

func (x *GetRelevanceScoresRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *GetRelevanceScoresRequest) GetDocuments() []*RetrievedDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *GetRelevanceScoresRequest) GetQueryText() string {
	if x != nil {
		return x.QueryText
	}
	return ""
}

func (x *GetRelevanceScoresRequest) GetOptions() map[string]string {
	if x != nil {
		return x.Options
	}
	return nil
}

type GetRelevanceScoresResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Success       bool                    `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                  `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Result        *RelevanceScoringResult `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Metadata      map[string]string       `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelevanceScoresResponse) Reset() {
	*x = GetRelevanceScoresResponse{}
	mi := &file_retrieval_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelevanceScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelevanceScoresResponse) ProtoMessage() {}

func (x *GetRelevanceScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelevanceScoresResponse.ProtoReflect.Descriptor instead.
func (*GetRelevanceScoresResponse) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{19}
}

func (x *GetRelevanceScoresResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRelevanceScoresResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetRelevanceScoresResponse) GetResult() *RelevanceScoringResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetRelevanceScoresResponse) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RelevanceScoringResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*DocumentScore       `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	Summary       *ScoringSummary        `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelevanceScoringResult) Reset() {
	*x = RelevanceScoringResult{}
	mi := &file_retrieval_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelevanceScoringResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelevanceScoringResult) ProtoMessage() {}

func (x *RelevanceScoringResult) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelevanceScoringResult.ProtoReflect.Descriptor instead.
func (*RelevanceScoringResult) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{20}
}

func (x *RelevanceScoringResult) GetScores() []*DocumentScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *RelevanceScoringResult) GetSummary() *ScoringSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type DocumentScore struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocumentId     string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	RelevanceScore float32                `protobuf:"fixed32,2,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	Components     []*ScoreComponent      `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DocumentScore) Reset() {
	*x = DocumentScore{}
	mi := &file_retrieval_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentScore) ProtoMessage() {}

func (x *DocumentScore) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentScore.ProtoReflect.Descriptor instead.
func (*DocumentScore) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{21}
}

func (x *DocumentScore) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DocumentScore) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *DocumentScore) GetComponents() []*ScoreComponent {
	if x != nil {
		return x.Components
	}
	return nil
}

type ScoreComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComponentName string                 `protobuf:"bytes,1,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
	Weight        float32                `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreComponent) Reset() {
	*x = ScoreComponent{}
	mi := &file_retrieval_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreComponent) ProtoMessage() {}

func (x *ScoreComponent) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreComponent.ProtoReflect.Descriptor instead.
func (*ScoreComponent) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{22}
}

func (x *ScoreComponent) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ScoreComponent) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ScoreComponent) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ScoringSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AverageScore  float32                `protobuf:"fixed32,1,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	MinScore      float32                `protobuf:"fixed32,2,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	MaxScore      float32                `protobuf:"fixed32,3,opt,name=max_score,json=maxScore,proto3" json:"max_score,omitempty"`
	ScoringMethod string                 `protobuf:"bytes,4,opt,name=scoring_method,json=scoringMethod,proto3" json:"scoring_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoringSummary) Reset() {
	*x = ScoringSummary{}
	mi := &file_retrieval_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoringSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoringSummary) ProtoMessage() {}

func (x *ScoringSummary) ProtoReflect() protoreflect.Message {
	mi := &file_retrieval_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoringSummary.ProtoReflect.Descriptor instead.
func (*ScoringSummary) Descriptor() ([]byte, []int) {
	return file_retrieval_service_proto_rawDescGZIP(), []int{23}
}

func (x *ScoringSummary) GetAverageScore() float32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *ScoringSummary) GetMinScore() float32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *ScoringSummary) GetMaxScore() float32 {
	if x != nil {
		return x.MaxScore
	}
	return 0
}

func (x *ScoringSummary) GetScoringMethod() string {
	if x != nil {
		return x.ScoringMethod
	}
	return ""
}

var File_retrieval_service_proto protoreflect.FileDescriptor

const file_retrieval_service_proto_rawDesc = "" +
	"\n" +
	"\x17retrieval_service.proto\x12\x1dai_platform.retrieval_service\"\xc2\x03\n" +
	"\x15SemanticSearchRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12'\n" +
	"\x0fcollection_name\x18\x03 \x01(\tR\x0ecollectionName\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12[\n" +
	"\afilters\x18\x05 \x03(\v2A.ai_platform.retrieval_service.SemanticSearchRequest.FiltersEntryR\afilters\x12[\n" +
	"\aoptions\x18\x06 \x03(\v2A.ai_platform.retrieval_service.SemanticSearchRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x02\n" +
	"\x16SemanticSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x03 \x01(\v2+.ai_platform.retrieval_service.SearchResultR\x06result\x12_\n" +
	"\bmetadata\x18\x04 \x03(\v2C.ai_platform.retrieval_service.SemanticSearchResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa6\x01\n" +
	"\fSearchResult\x12N\n" +
	"\tdocuments\x18\x01 \x03(\v20.ai_platform.retrieval_service.RetrievedDocumentR\tdocuments\x12F\n" +
	"\asummary\x18\x02 \x01(\v2,.ai_platform.retrieval_service.SearchSummaryR\asummary\"\xfd\x01\n" +
	"\x11RetrievedDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x02R\x05score\x12Z\n" +
	"\bmetadata\x18\x04 \x03(\v2>.ai_platform.retrieval_service.RetrievedDocument.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\rSearchSummary\x12#\n" +
	"\rtotal_results\x18\x01 \x01(\x05R\ftotalResults\x12$\n" +
	"\x0esearch_time_ms\x18\x02 \x01(\x02R\fsearchTimeMs\x12'\n" +
	"\x0fsearch_strategy\x18\x03 \x01(\tR\x0esearchStrategy\"\x8c\x04\n" +
	"\x13HybridSearchRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"query_text\x18\x02 \x01(\tR\tqueryText\x12'\n" +
	"\x0fcollection_name\x18\x03 \x01(\tR\x0ecollectionName\x12'\n" +
	"\x0fsemantic_weight\x18\x04 \x01(\x02R\x0esemanticWeight\x12%\n" +
	"\x0ekeyword_weight\x18\x05 \x01(\x02R\rkeywordWeight\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12Y\n" +
	"\afilters\x18\a \x03(\v2?.ai_platform.retrieval_service.HybridSearchRequest.FiltersEntryR\afilters\x12Y\n" +
	"\aoptions\x18\b \x03(\v2?.ai_platform.retrieval_service.HybridSearchRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\x14HybridSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x03 \x01(\v2+.ai_platform.retrieval_service.SearchResultR\x06result\x12]\n" +
	"\bmetadata\x18\x04 \x03(\v2A.ai_platform.retrieval_service.HybridSearchResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8e\x03\n" +
	"\x17FilterByMetadataRequest\x12'\n" +
	"\x0fcollection_name\x18\x01 \x01(\tR\x0ecollectionName\x12]\n" +
	"\afilters\x18\x02 \x03(\v2C.ai_platform.retrieval_service.FilterByMetadataRequest.FiltersEntryR\afilters\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12]\n" +
	"\aoptions\x18\x04 \x03(\v2C.ai_platform.retrieval_service.FilterByMetadataRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fFiltersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb3\x02\n" +
	"\x18FilterByMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12C\n" +
	"\x06result\x18\x03 \x01(\v2+.ai_platform.retrieval_service.FilterResultR\x06result\x12a\n" +
	"\bmetadata\x18\x04 \x03(\v2E.ai_platform.retrieval_service.FilterByMetadataResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xae\x01\n" +
	"\fFilterResult\x12N\n" +
	"\tdocuments\x18\x01 \x03(\v20.ai_platform.retrieval_service.RetrievedDocumentR\tdocuments\x12%\n" +
	"\x0etotal_filtered\x18\x02 \x01(\x05R\rtotalFiltered\x12'\n" +
	"\x0fapplied_filters\x18\x03 \x03(\tR\x0eappliedFilters\"\xc5\x02\n" +
	"\x13BuildContextRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12N\n" +
	"\tdocuments\x18\x02 \x03(\v20.ai_platform.retrieval_service.RetrievedDocumentR\tdocuments\x12,\n" +
	"\x12max_context_length\x18\x03 \x01(\x05R\x10maxContextLength\x12Y\n" +
	"\aoptions\x18\x04 \x03(\v2?.ai_platform.retrieval_service.BuildContextRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xac\x02\n" +
	"\x14BuildContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\x06result\x18\x03 \x01(\v2,.ai_platform.retrieval_service.ContextResultR\x06result\x12]\n" +
	"\bmetadata\x18\x04 \x03(\v2A.ai_platform.retrieval_service.BuildContextResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x94\x01\n" +
	"\rContextResult\x12\x18\n" +
	"\acontext\x18\x01 \x01(\tR\acontext\x12F\n" +
	"\asources\x18\x02 \x03(\v2,.ai_platform.retrieval_service.ContextSourceR\asources\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"x\n" +
	"\rContextSource\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12,\n" +
	"\x12used_chunk_indices\x18\x02 \x03(\x05R\x10usedChunkIndices\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\"\xc2\x02\n" +
	"\x12ExpandQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12%\n" +
	"\x0eoriginal_query\x18\x02 \x01(\tR\roriginalQuery\x12-\n" +
	"\x12expansion_strategy\x18\x03 \x01(\tR\x11expansionStrategy\x12%\n" +
	"\x0enum_expansions\x18\x04 \x01(\x05R\rnumExpansions\x12X\n" +
	"\aoptions\x18\x05 \x03(\v2>.ai_platform.retrieval_service.ExpandQueryRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb1\x02\n" +
	"\x13ExpandQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12K\n" +
	"\x06result\x18\x03 \x01(\v23.ai_platform.retrieval_service.QueryExpansionResultR\x06result\x12\\\n" +
	"\bmetadata\x18\x04 \x03(\v2@.ai_platform.retrieval_service.ExpandQueryResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x14QueryExpansionResult\x12W\n" +
	"\x10expanded_queries\x18\x01 \x03(\v2,.ai_platform.retrieval_service.ExpandedQueryR\x0fexpandedQueries\"~\n" +
	"\rExpandedQuery\x12\x1d\n" +
	"\n" +
	"query_text\x18\x01 \x01(\tR\tqueryText\x12'\n" +
	"\x0fexpansion_score\x18\x02 \x01(\x02R\x0eexpansionScore\x12%\n" +
	"\x0eexpansion_type\x18\x03 \x01(\tR\rexpansionType\"\xc2\x02\n" +
	"\x19GetRelevanceScoresRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12N\n" +
	"\tdocuments\x18\x02 \x03(\v20.ai_platform.retrieval_service.RetrievedDocumentR\tdocuments\x12\x1d\n" +
	"\n" +
	"query_text\x18\x03 \x01(\tR\tqueryText\x12_\n" +
	"\aoptions\x18\x04 \x03(\v2E.ai_platform.retrieval_service.GetRelevanceScoresRequest.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x02\n" +
	"\x1aGetRelevanceScoresResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12M\n" +
	"\x06result\x18\x03 \x01(\v25.ai_platform.retrieval_service.RelevanceScoringResultR\x06result\x12c\n" +
	"\bmetadata\x18\x04 \x03(\v2G.ai_platform.retrieval_service.GetRelevanceScoresResponse.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x16RelevanceScoringResult\x12D\n" +
	"\x06scores\x18\x01 \x03(\v2,.ai_platform.retrieval_service.DocumentScoreR\x06scores\x12G\n" +
	"\asummary\x18\x02 \x01(\v2-.ai_platform.retrieval_service.ScoringSummaryR\asummary\"\xa8\x01\n" +
	"\rDocumentScore\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12'\n" +
	"\x0frelevance_score\x18\x02 \x01(\x02R\x0erelevanceScore\x12M\n" +
	"\n" +
	"components\x18\x03 \x03(\v2-.ai_platform.retrieval_service.ScoreComponentR\n" +
	"components\"e\n" +
	"\x0eScoreComponent\x12%\n" +
	"\x0ecomponent_name\x18\x01 \x01(\tR\rcomponentName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x02R\x06weight\"\x96\x01\n" +
	"\x0eScoringSummary\x12#\n" +
	"\raverage_score\x18\x01 \x01(\x02R\faverageScore\x12\x1b\n" +
	"\tmin_score\x18\x02 \x01(\x02R\bminScore\x12\x1b\n" +
	"\tmax_score\x18\x03 \x01(\x02R\bmaxScore\x12%\n" +
	"\x0escoring_method\x18\x04 \x01(\tR\rscoringMethod2\x8b\x06\n" +
	"\x10RetrievalService\x12}\n" +
	"\x0eSemanticSearch\x124.ai_platform.retrieval_service.SemanticSearchRequest\x1a5.ai_platform.retrieval_service.SemanticSearchResponse\x12w\n" +
	"\fHybridSearch\x122.ai_platform.retrieval_service.HybridSearchRequest\x1a3.ai_platform.retrieval_service.HybridSearchResponse\x12\x83\x01\n" +
	"\x10FilterByMetadata\x126.ai_platform.retrieval_service.FilterByMetadataRequest\x1a7.ai_platform.retrieval_service.FilterByMetadataResponse\x12w\n" +
	"\fBuildContext\x122.ai_platform.retrieval_service.BuildContextRequest\x1a3.ai_platform.retrieval_service.BuildContextResponse\x12t\n" +
	"\vExpandQuery\x121.ai_platform.retrieval_service.ExpandQueryRequest\x1a2.ai_platform.retrieval_service.ExpandQueryResponse\x12\x89\x01\n" +
	"\x12GetRelevanceScores\x128.ai_platform.retrieval_service.GetRelevanceScoresRequest\x1a9.ai_platform.retrieval_service.GetRelevanceScoresResponseB2Z0sim-sekolah/internal/ai/grpc/pb/retrievalserviceb\x06proto3"

var (
	file_retrieval_service_proto_rawDescOnce sync.Once
	file_retrieval_service_proto_rawDescData []byte
)

func file_retrieval_service_proto_rawDescGZIP() []byte {
	file_retrieval_service_proto_rawDescOnce.Do(func() {
		file_retrieval_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_retrieval_service_proto_rawDesc), len(file_retrieval_service_proto_rawDesc)))
	})
	return file_retrieval_service_proto_rawDescData
}

var file_retrieval_service_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_retrieval_service_proto_goTypes = []any{
	(*SemanticSearchRequest)(nil),      // 0: ai_platform.retrieval_service.SemanticSearchRequest
	(*SemanticSearchResponse)(nil),     // 1: ai_platform.retrieval_service.SemanticSearchResponse
	(*SearchResult)(nil),               // 2: ai_platform.retrieval_service.SearchResult
	(*RetrievedDocument)(nil),          // 3: ai_platform.retrieval_service.RetrievedDocument
	(*SearchSummary)(nil),              // 4: ai_platform.retrieval_service.SearchSummary
	(*HybridSearchRequest)(nil),        // 5: ai_platform.retrieval_service.HybridSearchRequest
	(*HybridSearchResponse)(nil),       // 6: ai_platform.retrieval_service.HybridSearchResponse
	(*FilterByMetadataRequest)(nil),    // 7: ai_platform.retrieval_service.FilterByMetadataRequest
	(*FilterByMetadataResponse)(nil),   // 8: ai_platform.retrieval_service.FilterByMetadataResponse
	(*FilterResult)(nil),               // 9: ai_platform.retrieval_service.FilterResult
	(*BuildContextRequest)(nil),        // 10: ai_platform.retrieval_service.BuildContextRequest
	(*BuildContextResponse)(nil),       // 11: ai_platform.retrieval_service.BuildContextResponse
	(*ContextResult)(nil),              // 12: ai_platform.retrieval_service.ContextResult
	(*ContextSource)(nil),              // 13: ai_platform.retrieval_service.ContextSource
	(*ExpandQueryRequest)(nil),         // 14: ai_platform.retrieval_service.ExpandQueryRequest
	(*ExpandQueryResponse)(nil),        // 15: ai_platform.retrieval_service.ExpandQueryResponse
	(*QueryExpansionResult)(nil),       // 16: ai_platform.retrieval_service.QueryExpansionResult
	(*ExpandedQuery)(nil),              // 17: ai_platform.retrieval_service.ExpandedQuery
	(*GetRelevanceScoresRequest)(nil),  // 18: ai_platform.retrieval_service.GetRelevanceScoresRequest
	(*GetRelevanceScoresResponse)(nil), // 19: ai_platform.retrieval_service.GetRelevanceScoresResponse
	(*RelevanceScoringResult)(nil),     // 20: ai_platform.retrieval_service.RelevanceScoringResult
	(*DocumentScore)(nil),              // 21: ai_platform.retrieval_service.DocumentScore
	(*ScoreComponent)(nil),             // 22: ai_platform.retrieval_service.ScoreComponent
	(*ScoringSummary)(nil),             // 23: ai_platform.retrieval_service.ScoringSummary
	nil,                                // 24: ai_platform.retrieval_service.SemanticSearchRequest.FiltersEntry
	nil,                                // 25: ai_platform.retrieval_service.SemanticSearchRequest.OptionsEntry
	nil,                                // 26: ai_platform.retrieval_service.SemanticSearchResponse.MetadataEntry
	nil,                                // 27: ai_platform.retrieval_service.RetrievedDocument.MetadataEntry
	nil,                                // 28: ai_platform.retrieval_service.HybridSearchRequest.FiltersEntry
	nil,                                // 29: ai_platform.retrieval_service.HybridSearchRequest.OptionsEntry
	nil,                                // 30: ai_platform.retrieval_service.HybridSearchResponse.MetadataEntry
	nil,                                // 31: ai_platform.retrieval_service.FilterByMetadataRequest.FiltersEntry
	nil,                                // 32: ai_platform.retrieval_service.FilterByMetadataRequest.OptionsEntry
	nil,                                // 33: ai_platform.retrieval_service.FilterByMetadataResponse.MetadataEntry
	nil,                                // 34: ai_platform.retrieval_service.BuildContextRequest.OptionsEntry
	nil,                                // 35: ai_platform.retrieval_service.BuildContextResponse.MetadataEntry
	nil,                                // 36: ai_platform.retrieval_service.ExpandQueryRequest.OptionsEntry
	nil,                                // 37: ai_platform.retrieval_service.ExpandQueryResponse.MetadataEntry
	nil,                                // 38: ai_platform.retrieval_service.GetRelevanceScoresRequest.OptionsEntry
	nil,                                // 39: ai_platform.retrieval_service.GetRelevanceScoresResponse.MetadataEntry
}
var file_retrieval_service_proto_depIdxs = []int32{
	24, // 0: ai_platform.retrieval_service.SemanticSearchRequest.filters:type_name -> ai_platform.retrieval_service.SemanticSearchRequest.FiltersEntry
	25, // 1: ai_platform.retrieval_service.SemanticSearchRequest.options:type_name -> ai_platform.retrieval_service.SemanticSearchRequest.OptionsEntry
	2,  // 2: ai_platform.retrieval_service.SemanticSearchResponse.result:type_name -> ai_platform.retrieval_service.SearchResult
	26, // 3: ai_platform.retrieval_service.SemanticSearchResponse.metadata:type_name -> ai_platform.retrieval_service.SemanticSearchResponse.MetadataEntry
	3,  // 4: ai_platform.retrieval_service.SearchResult.documents:type_name -> ai_platform.retrieval_service.RetrievedDocument
	4,  // 5: ai_platform.retrieval_service.SearchResult.summary:type_name -> ai_platform.retrieval_service.SearchSummary
	27, // 6: ai_platform.retrieval_service.RetrievedDocument.metadata:type_name -> ai_platform.retrieval_service.RetrievedDocument.MetadataEntry
	28, // 7: ai_platform.retrieval_service.HybridSearchRequest.filters:type_name -> ai_platform.retrieval_service.HybridSearchRequest.FiltersEntry
	29, // 8: ai_platform.retrieval_service.HybridSearchRequest.options:type_name -> ai_platform.retrieval_service.HybridSearchRequest.OptionsEntry
	2,  // 9: ai_platform.retrieval_service.HybridSearchResponse.result:type_name -> ai_platform.retrieval_service.SearchResult
	30, // 10: ai_platform.retrieval_service.HybridSearchResponse.metadata:type_name -> ai_platform.retrieval_service.HybridSearchResponse.MetadataEntry
	31, // 11: ai_platform.retrieval_service.FilterByMetadataRequest.filters:type_name -> ai_platform.retrieval_service.FilterByMetadataRequest.FiltersEntry
	32, // 12: ai_platform.retrieval_service.FilterByMetadataRequest.options:type_name -> ai_platform.retrieval_service.FilterByMetadataRequest.OptionsEntry
	9,  // 13: ai_platform.retrieval_service.FilterByMetadataResponse.result:type_name -> ai_platform.retrieval_service.FilterResult
	33, // 14: ai_platform.retrieval_service.FilterByMetadataResponse.metadata:type_name -> ai_platform.retrieval_service.FilterByMetadataResponse.MetadataEntry
	3,  // 15: ai_platform.retrieval_service.FilterResult.documents:type_name -> ai_platform.retrieval_service.RetrievedDocument
	3,  // 16: ai_platform.retrieval_service.BuildContextRequest.documents:type_name -> ai_platform.retrieval_service.RetrievedDocument
	34, // 17: ai_platform.retrieval_service.BuildContextRequest.options:type_name -> ai_platform.retrieval_service.BuildContextRequest.OptionsEntry
	12, // 18: ai_platform.retrieval_service.BuildContextResponse.result:type_name -> ai_platform.retrieval_service.ContextResult
	35, // 19: ai_platform.retrieval_service.BuildContextResponse.metadata:type_name -> ai_platform.retrieval_service.BuildContextResponse.MetadataEntry
	13, // 20: ai_platform.retrieval_service.ContextResult.sources:type_name -> ai_platform.retrieval_service.ContextSource
	36, // 21: ai_platform.retrieval_service.ExpandQueryRequest.options:type_name -> ai_platform.retrieval_service.ExpandQueryRequest.OptionsEntry
	16, // 22: ai_platform.retrieval_service.ExpandQueryResponse.result:type_name -> ai_platform.retrieval_service.QueryExpansionResult
	37, // 23: ai_platform.retrieval_service.ExpandQueryResponse.metadata:type_name -> ai_platform.retrieval_service.ExpandQueryResponse.MetadataEntry
	17, // 24: ai_platform.retrieval_service.QueryExpansionResult.expanded_queries:type_name -> ai_platform.retrieval_service.ExpandedQuery
	3,  // 25: ai_platform.retrieval_service.GetRelevanceScoresRequest.documents:type_name -> ai_platform.retrieval_service.RetrievedDocument
	38, // 26: ai_platform.retrieval_service.GetRelevanceScoresRequest.options:type_name -> ai_platform.retrieval_service.GetRelevanceScoresRequest.OptionsEntry
	20, // 27: ai_platform.retrieval_service.GetRelevanceScoresResponse.result:type_name -> ai_platform.retrieval_service.RelevanceScoringResult
	39, // 28: ai_platform.retrieval_service.GetRelevanceScoresResponse.metadata:type_name -> ai_platform.retrieval_service.GetRelevanceScoresResponse.MetadataEntry
	21, // 29: ai_platform.retrieval_service.RelevanceScoringResult.scores:type_name -> ai_platform.retrieval_service.DocumentScore
	23, // 30: ai_platform.retrieval_service.RelevanceScoringResult.summary:type_name -> ai_platform.retrieval_service.ScoringSummary
	22, // 31: ai_platform.retrieval_service.DocumentScore.components:type_name -> ai_platform.retrieval_service.ScoreComponent
	0,  // 32: ai_platform.retrieval_service.RetrievalService.SemanticSearch:input_type -> ai_platform.retrieval_service.SemanticSearchRequest
	5,  // 33: ai_platform.retrieval_service.RetrievalService.HybridSearch:input_type -> ai_platform.retrieval_service.HybridSearchRequest
	7,  // 34: ai_platform.retrieval_service.RetrievalService.FilterByMetadata:input_type -> ai_platform.retrieval_service.FilterByMetadataRequest
	10, // 35: ai_platform.retrieval_service.RetrievalService.BuildContext:input_type -> ai_platform.retrieval_service.BuildContextRequest
	14, // 36: ai_platform.retrieval_service.RetrievalService.ExpandQuery:input_type -> ai_platform.retrieval_service.ExpandQueryRequest
	18, // 37: ai_platform.retrieval_service.RetrievalService.GetRelevanceScores:input_type -> ai_platform.retrieval_service.GetRelevanceScoresRequest
	1,  // 38: ai_platform.retrieval_service.RetrievalService.SemanticSearch:output_type -> ai_platform.retrieval_service.SemanticSearchResponse
	6,  // 39: ai_platform.retrieval_service.RetrievalService.HybridSearch:output_type -> ai_platform.retrieval_service.HybridSearchResponse
	8,  // 40: ai_platform.retrieval_service.RetrievalService.FilterByMetadata:output_type -> ai_platform.retrieval_service.FilterByMetadataResponse
	11, // 41: ai_platform.retrieval_service.RetrievalService.BuildContext:output_type -> ai_platform.retrieval_service.BuildContextResponse
	15, // 42: ai_platform.retrieval_service.RetrievalService.ExpandQuery:output_type -> ai_platform.retrieval_service.ExpandQueryResponse
	19, // 43: ai_platform.retrieval_service.RetrievalService.GetRelevanceScores:output_type -> ai_platform.retrieval_service.GetRelevanceScoresResponse
	38, // [38:44] is the sub-list for method output_type
	32, // [32:38] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_retrieval_service_proto_init() }
func file_retrieval_service_proto_init() {
	if File_retrieval_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_retrieval_service_proto_rawDesc), len(file_retrieval_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_retrieval_service_proto_goTypes,
		DependencyIndexes: file_retrieval_service_proto_depIdxs,
		MessageInfos:      file_retrieval_service_proto_msgTypes,
	}.Build()
	File_retrieval_service_proto = out.File
	file_retrieval_service_proto_goTypes = nil
	file_retrieval_service_proto_depIdxs = nil
}
