# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import parser_service_pb2 as parser__service__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in parser_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ParserServiceStub(object):
    """Parser Service - Fase 2.1
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseDocument = channel.unary_unary(
                '/ai_platform.parser_service.ParserService/ParseDocument',
                request_serializer=parser__service__pb2.ParseDocumentRequest.SerializeToString,
                response_deserializer=parser__service__pb2.ParseDocumentResponse.FromString,
                _registered_method=True)
        self.ParseText = channel.unary_unary(
                '/ai_platform.parser_service.ParserService/ParseText',
                request_serializer=parser__service__pb2.ParseTextRequest.SerializeToString,
                response_deserializer=parser__service__pb2.ParseTextResponse.FromString,
                _registered_method=True)
        self.ExtractTables = channel.unary_unary(
                '/ai_platform.parser_service.ParserService/ExtractTables',
                request_serializer=parser__service__pb2.ExtractTablesRequest.SerializeToString,
                response_deserializer=parser__service__pb2.ExtractTablesResponse.FromString,
                _registered_method=True)
        self.ExtractImages = channel.unary_unary(
                '/ai_platform.parser_service.ParserService/ExtractImages',
                request_serializer=parser__service__pb2.ExtractImagesRequest.SerializeToString,
                response_deserializer=parser__service__pb2.ExtractImagesResponse.FromString,
                _registered_method=True)
        self.ExtractOCR = channel.unary_unary(
                '/ai_platform.parser_service.ParserService/ExtractOCR',
                request_serializer=parser__service__pb2.ExtractOCRRequest.SerializeToString,
                response_deserializer=parser__service__pb2.ExtractOCRResponse.FromString,
                _registered_method=True)
        self.DetectLayout = channel.unary_unary(
                '/ai_platform.parser_service.ParserService/DetectLayout',
                request_serializer=parser__service__pb2.DetectLayoutRequest.SerializeToString,
                response_deserializer=parser__service__pb2.DetectLayoutResponse.FromString,
                _registered_method=True)


class ParserServiceServicer(object):
    """Parser Service - Fase 2.1
    """

    def ParseDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParseText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractOCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLayout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ParserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ParseDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseDocument,
                    request_deserializer=parser__service__pb2.ParseDocumentRequest.FromString,
                    response_serializer=parser__service__pb2.ParseDocumentResponse.SerializeToString,
            ),
            'ParseText': grpc.unary_unary_rpc_method_handler(
                    servicer.ParseText,
                    request_deserializer=parser__service__pb2.ParseTextRequest.FromString,
                    response_serializer=parser__service__pb2.ParseTextResponse.SerializeToString,
            ),
            'ExtractTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractTables,
                    request_deserializer=parser__service__pb2.ExtractTablesRequest.FromString,
                    response_serializer=parser__service__pb2.ExtractTablesResponse.SerializeToString,
            ),
            'ExtractImages': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractImages,
                    request_deserializer=parser__service__pb2.ExtractImagesRequest.FromString,
                    response_serializer=parser__service__pb2.ExtractImagesResponse.SerializeToString,
            ),
            'ExtractOCR': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractOCR,
                    request_deserializer=parser__service__pb2.ExtractOCRRequest.FromString,
                    response_serializer=parser__service__pb2.ExtractOCRResponse.SerializeToString,
            ),
            'DetectLayout': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLayout,
                    request_deserializer=parser__service__pb2.DetectLayoutRequest.FromString,
                    response_serializer=parser__service__pb2.DetectLayoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_platform.parser_service.ParserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_platform.parser_service.ParserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ParserService(object):
    """Parser Service - Fase 2.1
    """

    @staticmethod
    def ParseDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.parser_service.ParserService/ParseDocument',
            parser__service__pb2.ParseDocumentRequest.SerializeToString,
            parser__service__pb2.ParseDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParseText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.parser_service.ParserService/ParseText',
            parser__service__pb2.ParseTextRequest.SerializeToString,
            parser__service__pb2.ParseTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.parser_service.ParserService/ExtractTables',
            parser__service__pb2.ExtractTablesRequest.SerializeToString,
            parser__service__pb2.ExtractTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.parser_service.ParserService/ExtractImages',
            parser__service__pb2.ExtractImagesRequest.SerializeToString,
            parser__service__pb2.ExtractImagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractOCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.parser_service.ParserService/ExtractOCR',
            parser__service__pb2.ExtractOCRRequest.SerializeToString,
            parser__service__pb2.ExtractOCRResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectLayout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_platform.parser_service.ParserService/DetectLayout',
            parser__service__pb2.DetectLayoutRequest.SerializeToString,
            parser__service__pb2.DetectLayoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
