// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: strategic_analysis_service.proto

package strategicanalysisservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	StrategicAnalysisService_AnalyzeSWOT_FullMethodName               = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/AnalyzeSWOT"
	StrategicAnalysisService_SuggestSWOTItems_FullMethodName          = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/SuggestSWOTItems"
	StrategicAnalysisService_AnalyzeRootCause_FullMethodName          = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/AnalyzeRootCause"
	StrategicAnalysisService_GenerateFiveWhys_FullMethodName          = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/GenerateFiveWhys"
	StrategicAnalysisService_AnalyzeFishbone_FullMethodName           = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/AnalyzeFishbone"
	StrategicAnalysisService_SuggestFishboneCategories_FullMethodName = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/SuggestFishboneCategories"
	StrategicAnalysisService_GenerateKSPContent_FullMethodName        = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/GenerateKSPContent"
	StrategicAnalysisService_GenerateKSPSection_FullMethodName        = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/GenerateKSPSection"
	StrategicAnalysisService_IntegrateAnalysisData_FullMethodName     = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/IntegrateAnalysisData"
	StrategicAnalysisService_HealthCheck_FullMethodName               = "/ai_platform.strategic_analysis_service.StrategicAnalysisService/HealthCheck"
)

// StrategicAnalysisServiceClient is the client API for StrategicAnalysisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StrategicAnalysisServiceClient interface {
	// SWOT Analysis
	AnalyzeSWOT(ctx context.Context, in *AnalyzeSWOTRequest, opts ...grpc.CallOption) (*AnalyzeSWOTResponse, error)
	SuggestSWOTItems(ctx context.Context, in *SuggestSWOTItemsRequest, opts ...grpc.CallOption) (*SuggestSWOTItemsResponse, error)
	// Root Cause Analysis
	AnalyzeRootCause(ctx context.Context, in *AnalyzeRootCauseRequest, opts ...grpc.CallOption) (*AnalyzeRootCauseResponse, error)
	GenerateFiveWhys(ctx context.Context, in *GenerateFiveWhysRequest, opts ...grpc.CallOption) (*GenerateFiveWhysResponse, error)
	// Fishbone Analysis
	AnalyzeFishbone(ctx context.Context, in *AnalyzeFishboneRequest, opts ...grpc.CallOption) (*AnalyzeFishboneResponse, error)
	SuggestFishboneCategories(ctx context.Context, in *SuggestFishboneCategoriesRequest, opts ...grpc.CallOption) (*SuggestFishboneCategoriesResponse, error)
	// KSP Content Generation
	GenerateKSPContent(ctx context.Context, in *GenerateKSPContentRequest, opts ...grpc.CallOption) (*GenerateKSPContentResponse, error)
	GenerateKSPSection(ctx context.Context, in *GenerateKSPSectionRequest, opts ...grpc.CallOption) (*GenerateKSPSectionResponse, error)
	// Cross-Analysis Integration
	IntegrateAnalysisData(ctx context.Context, in *IntegrateAnalysisDataRequest, opts ...grpc.CallOption) (*IntegrateAnalysisDataResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type strategicAnalysisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStrategicAnalysisServiceClient(cc grpc.ClientConnInterface) StrategicAnalysisServiceClient {
	return &strategicAnalysisServiceClient{cc}
}

func (c *strategicAnalysisServiceClient) AnalyzeSWOT(ctx context.Context, in *AnalyzeSWOTRequest, opts ...grpc.CallOption) (*AnalyzeSWOTResponse, error) {
	out := new(AnalyzeSWOTResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_AnalyzeSWOT_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) SuggestSWOTItems(ctx context.Context, in *SuggestSWOTItemsRequest, opts ...grpc.CallOption) (*SuggestSWOTItemsResponse, error) {
	out := new(SuggestSWOTItemsResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_SuggestSWOTItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) AnalyzeRootCause(ctx context.Context, in *AnalyzeRootCauseRequest, opts ...grpc.CallOption) (*AnalyzeRootCauseResponse, error) {
	out := new(AnalyzeRootCauseResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_AnalyzeRootCause_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) GenerateFiveWhys(ctx context.Context, in *GenerateFiveWhysRequest, opts ...grpc.CallOption) (*GenerateFiveWhysResponse, error) {
	out := new(GenerateFiveWhysResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_GenerateFiveWhys_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) AnalyzeFishbone(ctx context.Context, in *AnalyzeFishboneRequest, opts ...grpc.CallOption) (*AnalyzeFishboneResponse, error) {
	out := new(AnalyzeFishboneResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_AnalyzeFishbone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) SuggestFishboneCategories(ctx context.Context, in *SuggestFishboneCategoriesRequest, opts ...grpc.CallOption) (*SuggestFishboneCategoriesResponse, error) {
	out := new(SuggestFishboneCategoriesResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_SuggestFishboneCategories_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) GenerateKSPContent(ctx context.Context, in *GenerateKSPContentRequest, opts ...grpc.CallOption) (*GenerateKSPContentResponse, error) {
	out := new(GenerateKSPContentResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_GenerateKSPContent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) GenerateKSPSection(ctx context.Context, in *GenerateKSPSectionRequest, opts ...grpc.CallOption) (*GenerateKSPSectionResponse, error) {
	out := new(GenerateKSPSectionResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_GenerateKSPSection_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) IntegrateAnalysisData(ctx context.Context, in *IntegrateAnalysisDataRequest, opts ...grpc.CallOption) (*IntegrateAnalysisDataResponse, error) {
	out := new(IntegrateAnalysisDataResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_IntegrateAnalysisData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *strategicAnalysisServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, StrategicAnalysisService_HealthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StrategicAnalysisServiceServer is the server API for StrategicAnalysisService service.
// All implementations must embed UnimplementedStrategicAnalysisServiceServer
// for forward compatibility
type StrategicAnalysisServiceServer interface {
	// SWOT Analysis
	AnalyzeSWOT(context.Context, *AnalyzeSWOTRequest) (*AnalyzeSWOTResponse, error)
	SuggestSWOTItems(context.Context, *SuggestSWOTItemsRequest) (*SuggestSWOTItemsResponse, error)
	// Root Cause Analysis
	AnalyzeRootCause(context.Context, *AnalyzeRootCauseRequest) (*AnalyzeRootCauseResponse, error)
	GenerateFiveWhys(context.Context, *GenerateFiveWhysRequest) (*GenerateFiveWhysResponse, error)
	// Fishbone Analysis
	AnalyzeFishbone(context.Context, *AnalyzeFishboneRequest) (*AnalyzeFishboneResponse, error)
	SuggestFishboneCategories(context.Context, *SuggestFishboneCategoriesRequest) (*SuggestFishboneCategoriesResponse, error)
	// KSP Content Generation
	GenerateKSPContent(context.Context, *GenerateKSPContentRequest) (*GenerateKSPContentResponse, error)
	GenerateKSPSection(context.Context, *GenerateKSPSectionRequest) (*GenerateKSPSectionResponse, error)
	// Cross-Analysis Integration
	IntegrateAnalysisData(context.Context, *IntegrateAnalysisDataRequest) (*IntegrateAnalysisDataResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedStrategicAnalysisServiceServer()
}

// UnimplementedStrategicAnalysisServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStrategicAnalysisServiceServer struct {
}

func (UnimplementedStrategicAnalysisServiceServer) AnalyzeSWOT(context.Context, *AnalyzeSWOTRequest) (*AnalyzeSWOTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeSWOT not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) SuggestSWOTItems(context.Context, *SuggestSWOTItemsRequest) (*SuggestSWOTItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestSWOTItems not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) AnalyzeRootCause(context.Context, *AnalyzeRootCauseRequest) (*AnalyzeRootCauseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeRootCause not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) GenerateFiveWhys(context.Context, *GenerateFiveWhysRequest) (*GenerateFiveWhysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateFiveWhys not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) AnalyzeFishbone(context.Context, *AnalyzeFishboneRequest) (*AnalyzeFishboneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeFishbone not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) SuggestFishboneCategories(context.Context, *SuggestFishboneCategoriesRequest) (*SuggestFishboneCategoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SuggestFishboneCategories not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) GenerateKSPContent(context.Context, *GenerateKSPContentRequest) (*GenerateKSPContentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKSPContent not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) GenerateKSPSection(context.Context, *GenerateKSPSectionRequest) (*GenerateKSPSectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKSPSection not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) IntegrateAnalysisData(context.Context, *IntegrateAnalysisDataRequest) (*IntegrateAnalysisDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IntegrateAnalysisData not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedStrategicAnalysisServiceServer) mustEmbedUnimplementedStrategicAnalysisServiceServer() {
}

// UnsafeStrategicAnalysisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StrategicAnalysisServiceServer will
// result in compilation errors.
type UnsafeStrategicAnalysisServiceServer interface {
	mustEmbedUnimplementedStrategicAnalysisServiceServer()
}

func RegisterStrategicAnalysisServiceServer(s grpc.ServiceRegistrar, srv StrategicAnalysisServiceServer) {
	s.RegisterService(&StrategicAnalysisService_ServiceDesc, srv)
}

func _StrategicAnalysisService_AnalyzeSWOT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSWOTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).AnalyzeSWOT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_AnalyzeSWOT_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).AnalyzeSWOT(ctx, req.(*AnalyzeSWOTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_SuggestSWOTItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestSWOTItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).SuggestSWOTItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_SuggestSWOTItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).SuggestSWOTItems(ctx, req.(*SuggestSWOTItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_AnalyzeRootCause_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRootCauseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).AnalyzeRootCause(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_AnalyzeRootCause_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).AnalyzeRootCause(ctx, req.(*AnalyzeRootCauseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_GenerateFiveWhys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateFiveWhysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).GenerateFiveWhys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_GenerateFiveWhys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).GenerateFiveWhys(ctx, req.(*GenerateFiveWhysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_AnalyzeFishbone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFishboneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).AnalyzeFishbone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_AnalyzeFishbone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).AnalyzeFishbone(ctx, req.(*AnalyzeFishboneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_SuggestFishboneCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestFishboneCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).SuggestFishboneCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_SuggestFishboneCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).SuggestFishboneCategories(ctx, req.(*SuggestFishboneCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_GenerateKSPContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKSPContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).GenerateKSPContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_GenerateKSPContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).GenerateKSPContent(ctx, req.(*GenerateKSPContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_GenerateKSPSection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKSPSectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).GenerateKSPSection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_GenerateKSPSection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).GenerateKSPSection(ctx, req.(*GenerateKSPSectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_IntegrateAnalysisData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntegrateAnalysisDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).IntegrateAnalysisData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_IntegrateAnalysisData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).IntegrateAnalysisData(ctx, req.(*IntegrateAnalysisDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StrategicAnalysisService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StrategicAnalysisServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StrategicAnalysisService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StrategicAnalysisServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StrategicAnalysisService_ServiceDesc is the grpc.ServiceDesc for StrategicAnalysisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StrategicAnalysisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_platform.strategic_analysis_service.StrategicAnalysisService",
	HandlerType: (*StrategicAnalysisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeSWOT",
			Handler:    _StrategicAnalysisService_AnalyzeSWOT_Handler,
		},
		{
			MethodName: "SuggestSWOTItems",
			Handler:    _StrategicAnalysisService_SuggestSWOTItems_Handler,
		},
		{
			MethodName: "AnalyzeRootCause",
			Handler:    _StrategicAnalysisService_AnalyzeRootCause_Handler,
		},
		{
			MethodName: "GenerateFiveWhys",
			Handler:    _StrategicAnalysisService_GenerateFiveWhys_Handler,
		},
		{
			MethodName: "AnalyzeFishbone",
			Handler:    _StrategicAnalysisService_AnalyzeFishbone_Handler,
		},
		{
			MethodName: "SuggestFishboneCategories",
			Handler:    _StrategicAnalysisService_SuggestFishboneCategories_Handler,
		},
		{
			MethodName: "GenerateKSPContent",
			Handler:    _StrategicAnalysisService_GenerateKSPContent_Handler,
		},
		{
			MethodName: "GenerateKSPSection",
			Handler:    _StrategicAnalysisService_GenerateKSPSection_Handler,
		},
		{
			MethodName: "IntegrateAnalysisData",
			Handler:    _StrategicAnalysisService_IntegrateAnalysisData_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _StrategicAnalysisService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "strategic_analysis_service.proto",
}
